### ISSUE TITLE
NPM has no README.md

### ISSUE THREAD

**Issue by mikkoh** [thelinmichael/spotify-web-api-node#106]
I know with one of my friends packages the `README.md` file was not distributed to NPM. Some bug in NPM. Just noticed this package does not have a README on [NPM either](https://www.npmjs.com/package/spotify-web-api-node).

**Comment by JMPerez** [comment]
Not sure why this is happening. I wonder if https://github.com/npm/registry/issues/42#issuecomment-243428303 can help.

**Comment by JMPerez** [comment]
The package has regained its README and it also shows up when installing the dependency.
