### ISSUE TITLE
Issue of IOS devices and IE11

### ISSUE THREAD

**Issue by Aravind-WMG** [thelinmichael/spotify-web-api-node#108]
i was developing one app  to follow me by others and facing some issues on ios and IE11.

ios issue : unable get authentication...when ever i am clicking the authentication button to follow me, nothing is happening.but this works fine on android chrome firefox. When i add "/?" at the end of redirect URI, it will works fine.pls help on this.

IE11 issue....i am unable to follow anyone when i am using IE11.i guess promises function are not working on IE11....pls help onthis too..

Thanks !

**Comment by JMPerez** [comment]
@Aravind-WMG It's a bit difficult to know what's going on, and whether the issue has to do with the library itself. I recommend you to provide a concise piece of code that we can look at to help you.

**Comment by Aravind-WMG** [comment]
@JMPerez 

`var artistID = '';
var artistIDArr = [''];
var playlistID = '';
var clientId = ';
var redirect_url = 'http://xxx.com**/?**';

jQuery(document).ready(function(){
	       jQuery('a#follow-artist').live('click', function(e) {
			 //console.log('here');
            e.preventDefault();
			
            var client_id = clientId;// Your client id
            var redirect_uri = redirect_url;// Your redirect uri
			
            var state = generateRandomString(16);
            localStorage.setItem(stateKey, state);
            var scope = 'user-read-email user-follow-modify playlist-modify-public';
            var url = 'https://accounts.spotify.com/authorize';
            url += '?response_type=token';
            url += '&client_id=' + encodeURIComponent(client_id);
            url += '&scope=' + encodeURIComponent(scope);
            url += '&redirect_uri=' + encodeURIComponent(redirect_uri);
            url += '&state=' + encodeURIComponent(state);
            window.location = url;
        });
});
   
function generateRandomString(length) {
        var text = '';
        var possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        for (var i = 0; i < length; i++) {
            text += possible.charAt(Math.floor(Math.random() * possible.length));
        }
        return text;
}
	

var stateKey = 'spotify_auth_state';
function getHashParams() {
        var hashParams = {};
        var e, r = /([^&;=]+)=?([^&;]*)/g, q = window.location.hash.substring(1);
        while ( e = r.exec(q)) {
            hashParams[e[1]] = decodeURIComponent(e[2]);
        }
        return hashParams;
}
	
var params = getHashParams();
var access_token = params.access_token, state = params.state, storedState = localStorage.getItem(stateKey);
    if (access_token && (state == null || state !== storedState)) {
        alert('There was an error during the authentication');
    } else {
        localStorage.removeItem(stateKey);
        if (access_token) {
            var spotifyApi = new SpotifyWebApi();
            spotifyApi.setAccessToken(access_token);
			spotifyApi.followUsers(artistIDArr).then(function(data){
              console.log('Followed');
				
          },function(err) {
                console.log('Follow error', err);
             
            });          
            spotifyApi.followPlaylist(artistID,playlistID)**.then(**function(data){
               console.log('Followed Playlist');
          },function(err) {
                console.log('Follow error', err);
             
            });

           
        } 
     }
	 `

This is my code.Please let me know if you need anything else

Thanks !

**Comment by tetreault** [comment]
@ Aravind-WMG please format your code properly for better readability especially when asking for help! Just wrap your code block in triple backticks and itll format the whole block.

**Comment by JMPerez** [comment]
@Aravind-WMG did you manage to solve the issue?
