### ISSUE TITLE
How to use OAuth token to create playlist?

### ISSUE THREAD

**Issue by kabirvirji** [thelinmichael/spotify-web-api-node#110]
I'm trying to create a playlist but I need to authenticate. I'm using the client credentials grant. 

I'm able to get the access token, but `authorizationCodeGrant` is failing when I pass the token in. How should I change this so that `authorizationCodeGrant` works? Is this the correct way to be creating a playlist?

```js
// Create the api object with the credentials
var spotifyApi = new SpotifyWebApi({
  clientId : config.spotifyid,
  clientSecret : config.spotifysecret
});

// Retrieve an access token.
spotifyApi.clientCredentialsGrant()
  .then(function(data) {
    console.log('The access token expires in ' + data.body['expires_in']);
    console.log('The access token is ' + data.body['access_token']);

    // Save the access token so that it's used in future calls
    spotifyApi.setAccessToken(data.body['access_token']);
    const authorizationCode = data.body['access_token'];

	  spotifyApi.authorizationCodeGrant(authorizationCode)
	  .then(function(data) {
	    // spotifyApi.setAccessToken(data.body['access_token']);
		return spotifyApi.createPlaylist('kabirvirji', 'My Cool Playlist', { 'public' : false })
		  .then(function(data) {
		    console.log('Created playlist!');
		  }, function(err) {
		    console.log('Something went wrong!', err);
		  });
		}, function(err) {
			console.log('authorizationCodeGrant error', err);
		});

// This is the error being thrown
  }, function(err) {
        console.log('Something went wrong when retrieving an access token', err);
  });
```

**Comment by JMPerez** [comment]
@kabirvirji I recommend you to go through the [Spotify Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/). In order to create playlists you need authorization from the user, and for that you need to implement the Client Credentials or Authorization Code flow.

In both cases you need a user to log in, and then let them grant you access to the [scope](https://developer.spotify.com/web-api/using-scopes/) needs to create a playlist (`playlist-modify-public` or `playlist-modify-private` depending on the visibility of the playlist you want to create).

You can start with a basic example as described in the [beginner's tutorial](https://developer.spotify.com/web-api/tutorial/).

**Comment by tetreault** [comment]
@JMPerez I don't understand what Im doing wrong here. I copied the above code that @kabirvirji posted, as well Spotify's own example [here](https://raw.githubusercontent.com/spotify/web-api-auth-examples/master/client_credentials/app.js). Every attempt I make to try and obtain a client token to just fetch playlist data keeps failing. Can you help if you have a moment? It'd be greatly appreciated. 

```javascript
'use strict';

import express from 'express';
import path from 'path';
import fs from 'fs';
import http from 'http';
import https from 'https';
import Clarifai from 'clarifai';
import request from 'request'; 
import SpotifyWebApi from 'spotify-web-api-node';
import config from './config';
import bodyParser from 'body-parser';
import CircularJSON from 'circular-json';

const app = express();

app.use(express.static(path.join(__dirname, '../public')));
app.use(bodyParser.json({limit: '6mb'}));
app.set('view engine', 'ejs');

// Router for navigating us to the site. 
app.get('/', (req, res) => {
  res.render('pages/index.ejs');
});

// Router for generating the Spotify playlist
app.get('/spotify', (req, res) => {
  const spotifyValues = {
    user: config.spotify.user,
    clientId: config.spotify.id,
    clientSecret: config.spotify.secret,
    redirectUri: 'http://XXXXXXXXX.compute.amazonaws.com/'
  };

  // Create the api object with the credentials
  var spotifyApi = new SpotifyWebApi({
    clientId : config.spotify.id,
    clientSecret : config.spotify.secret
  });

  // Retrieve an access token.
  spotifyApi.clientCredentialsGrant()
  .then(function(data) {
    console.log('The access token expires in ' + data.body['expires_in']);
    console.log('The access token is ' + data.body['access_token']);

    // Save the access token so that it's used in future calls
    spotifyApi.setAccessToken(data.body['access_token']);
    const authorizationCode = data.body['access_token'];

    console.log('auth code again', authorizationCode);

  }, function(err) {
    console.log('Something went wrong when retrieving an access token', err);
  });

  if (config.debug) console.log('A call was made to the spotify endpoint');

});


app.listen(config.ports.http);

if (config.debug) console.log(`App is running on ${config.ports.http}.`);
```

**Comment by tetreault** [comment]
To make the question a bit more pointed -- I created a "mixtape account". The only action ill be performing is fetching playlists I created on this account and dumping the contents into a site run on an EC2 instance.

**Comment by JMPerez** [comment]
@tetreault This should work if you are inputting the right client id and secret. Note that you don't need this bit:

```js
  const spotifyValues = {
    user: config.spotify.user,
    clientId: config.spotify.id,
    clientSecret: config.spotify.secret,
    redirectUri: 'http://XXXXXXXXX.compute.amazonaws.com/'
  };
```

Not sure what might be failing to be honest. Your code looks fine.

**Comment by tetreault** [comment]
Thank you for your prompt response @JMPerez ! Yes correct, that was left over from when I attempted using the straight up Spotify Web API I just forgot to remove it. 

I'm really at a loss. Nothing of Spotify's is working for me, I even tried the cURL example in the [auth guide](https://developer.spotify.com/web-api/authorization-guide/) using a valid base64 representation of my ID & Secret and that didn't even work - it just yields: `{"error":"invalid_client","error_description":"Invalid client"}`.

**Comment by JMPerez** [comment]
@tetreault the client credentials flow should work. I just created [this PR](https://github.com/thelinmichael/spotify-web-api-node/pull/113) with a client id and secret and it passes the tests, also in latest node version.

Also, your issue is different from @kabirvirji's, which I think should be solved by now, so it might be worth it opening a new issue.

**Comment by JMPerez** [comment]
Closing the issue due to inactivity. Feel free to reopen if needed.
