### ISSUE TITLE
Missing "Web API Connect Endpoints" support

### ISSUE THREAD

**Issue by JMPerez** [thelinmichael/spotify-web-api-node#114]
We should add support for these endpoints -> https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/

**Comment by cmseaton42** [comment]
This is exactly what I need

**Comment by orchestor** [comment]
I would love to have this endpoint either.

**Comment by fjaguero** [comment]
There is an open PR regarding this (#121). It would be awesome to merge this, I'm also waiting for it.

**Comment by JMPerez** [comment]
Closing since these are already implemented.
