### ISSUE TITLE
Internal Server error when trying to access playlists

### ISSUE THREAD

**Issue by sadmanf** [thelinmichael/spotify-web-api-node#122]
I tried using my accessToken on [the API console](https://developer.spotify.com/web-api/console/get-playlists/) and it printed out the JSON just fine. However,  when I tried to run the curl command that it produced, I got the following:

```
{
  "error" : {
    "status" : 500,
    "message" : "Server error."
  }
}
```

I'm able to use spotifyApi.getMe() to access the current authorized user, but when I try to use spotifyApi.getUserPlaylists(), it gives me an Internal Server Error.

This is my code for that portion:

```
spotifyApi.authorizationCodeGrant(req.query.code)
	  .then(function(data) {
	    console.log('The token expires in ' + data.body['expires_in']);
	    console.log('The access token is ' + data.body['access_token']);
	    console.log('The refresh token is ' + data.body['refresh_token']);

	    spotifyApi.setAccessToken(data.body['access_token']);
	    spotifyApi.setRefreshToken(data.body['refresh_token']);
	    return spotifyApi.getMe();
	  }, function(err) {
	    console.log('not authorized!', err);
	  })
	  .then(function(data){
	  	console.log(data.body.id);
	  	return spotifyApi.getUserPlaylists(data.body.id);
	  }, function(err) {
	  	console.log(err);
	  })
	  .then(function(data){
	  	console.log(data);
	  }, function(err) {
	    console.log(err);
	  });
```

**Comment by JMPerez** [comment]
@sadmanf this is likely an issue on Spotify's side. I'll close the ticket for now, but feel free to reopen if you see this happening again.
