### ISSUE TITLE
addTracksToPlaylist 'Bad Request' with lots of tracks

### ISSUE THREAD

**Issue by malexanderboyd** [thelinmichael/spotify-web-api-node#124]
Hi! I'm trying to use the addTracksToPlaylist() function, but I'm getting the error:

`{ [WebapiError: Bad Request] name: 'WebapiError', message: 'Bad Request', statusCode: 400 }`

I'm sending an array of tracks of the form 'spotify:track:ID' but the array contains about 150-200 tracks at a time.

This same function works however with a smaller array of tracks (sending around 50 tracks at a time), any ideas? I'm using the latest version

**Comment by JMPerez** [comment]
@malexanderboyd You can add up to 100 tracks at once. The function makes a request to [the endpoint](https://developer.spotify.com/web-api/add-tracks-to-playlist/) which has this length constraint.
