### ISSUE TITLE
Play/pause function support?

### ISSUE THREAD

**Issue by orchestor** [thelinmichael/spotify-web-api-node#125]
I am wondering are there functions to support play/pause etc endpoint?
 

https://developer.spotify.com/web-api/pause-a-users-playback/

any pointer on this?

**Comment by orchestor** [comment]
I found spotify-web-api-js support new api. Any plan for this repo?

**Comment by MileanCo** [comment]
I'm also looking for this; just need to play the 30 second sample that these endpoints offer -
https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/

**Comment by JMPerez** [comment]
Closing this as it's already implemented.
