### ISSUE TITLE
Add support for 'currently-playing'

### ISSUE THREAD

**Issue by AlexGustafsson** [thelinmichael/spotify-web-api-node#130]
The Spotify Web API has somewhat recently received some beta features such as the long-awaited receival of the currently playing object.

https://developer.spotify.com/web-api/get-the-users-currently-playing-track/

Support for this feature should be added (as well as potential other new features)

**Comment by pedro-otero** [comment]
Check #114

**Comment by AlexGustafsson** [comment]
I did some searching but I obviously failed to find that issue. Thanks for the info!
