### ISSUE TITLE
Received tokens do not seem to work

### ISSUE THREAD

**Issue by C-D-Lewis** [thelinmichael/spotify-web-api-node#133]
I've been writing some simple test code to try out this promising looking library. I've managed to get as far as to successfully receive and store the access token and refresh token via `authorizationCodeGrant()`, and set these on the API object using `setAccessToken()` and `setRefreshToken()`.

Yet, when I use the same object to call `getMyCurrentPlaybackState()` (my end goal for my use case), I get the following error:
```
{ [WebapiError: Unauthorized] name: 'WebapiError', message: 'Unauthorized', statusCode: 401 }
```

Have I missed some non-obvious authentication step? If not, what else do I need to do to use this API call? Thanks in advance.

**Comment by jpiepkow** [comment]
Make sure when requesting the tokens you have the right scope requested for the calls you plan to make.

**Comment by C-D-Lewis** [comment]
Thanks for the response. I'm having trouble finding which is the correct scope, or any kind of list, really. Can you point me somewhere I can find the right scope? Thanks.

**Comment by C-D-Lewis** [comment]
@jpiepkow I added the user-read-currently-playing and user-read-playback-state scopes, and it now works!
