### ISSUE TITLE
Feasibility question: Play (random) song?

### ISSUE THREAD

**Issue by rejas** [thelinmichael/spotify-web-api-node#134]
HI there,
I am trying to pimp my MagicMirror^2 project with a module that turns on music on voice-command. Now I am pondering if I can use your lib to access spotify and get some random music from it that I can then playback on the raspberry it would run on. 

If I understand correctly I can use the client_credentials grantType to get access to the spotify web api and get infos about artists albums etc. But can I also a) get a random song or a public playlist and b) get a stream-uri that I can then pass to a media player lib? 

Thanks in advance

**Comment by JMPerez** [comment]
The library is just a wrapper around Spotify's Web API endpoints. Unfortunately, there is no endpoint to select a random song nor get a stream that you can pass to a media player.
