### ISSUE TITLE
Currently playing?

### ISSUE THREAD

**Issue by simonculus** [thelinmichael/spotify-web-api-node#135]
Are there any/will there be any way to get a users currently playing track? I've read through the examples and I can't seem to find anything like that, am I just being oblivious, or are there no way to do it?

**Comment by jpiepkow** [comment]
https://github.com/thelinmichael/spotify-web-api-node/pull/121

**Comment by jpiepkow** [comment]
Can use the player endpoint added there.

**Comment by simonculus** [comment]
I'm not sure if I understand what you mean 🤔

**Comment by jpiepkow** [comment]
Looks like the getMyCurrentPlaybackState function was added in that pull request that was merged in. @simonculus does not look like readme is updated so you will have to look through the code for what the function takes.

**Comment by jpiepkow** [comment]
https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/spotify-web-api.js

**Comment by simonculus** [comment]
Ah, thanks! Now I just need to figure out what parameters to put there, lol.
