### ISSUE TITLE
Add API limitations to readme documentation?

### ISSUE THREAD

**Issue by vpicone** [thelinmichael/spotify-web-api-node#136]
If some folks are like me, they don't bother to read the Spotify Endpoints for each call. Would it be helpful for me to go through the read me and thoughtfully add comments for different limitations? This like how you can only follow 50 artists at a time and the default playlist fetching is 20 playlists but can be increased to 50 etc.

**Comment by JMPerez** [comment]
Yes, this would be something useful. Even throwing errors if limits are exceeded or, ideally, handle collections transparently within the wrapper.

Unfortunately this is not supported at the moment, but let's keep this ticket open for reference.
