### ISSUE TITLE
Play Song?

### ISSUE THREAD

**Issue by herohamp** [thelinmichael/spotify-web-api-node#138]
Can I make it play a song on my account so that an amazon alexa will play a song I select?

**Comment by victor-m-1994** [comment]
I just added this ability in my recent pull request, 163. If it's merged, then you will be able to specify device_id.

**Comment by ELIDJEAKA** [comment]
@victor-m-1994, have you got a code for playing with a device_id ?

**Comment by bluepuma77** [comment]
+1 Would be great to have this basic function in the next release

Similar to https://github.com/thelinmichael/spotify-web-api-node/issues/170

**Comment by bluepuma77** [comment]
Get device_id
`
spotifyApi.getMyDevices()
  .then(function(data) {
    console.log('Data', data.body);
  }, function(err) {
    console.error(err);
  });
`

**Comment by JMPerez** [comment]
I'm happy to inform that this has been implemented and shipped in version 3.0.0.

**Comment by busybox11** [comment]
Hey,
I'm sorry to bring this topic back to life but I don't understand how this works.
I'd like to play a song via an ID / URI to the currently used player (if possible I'd like to also be able to play artists, albums, individual songs, playlists, and with the "Shuffle play" feature).
How can I pass an ID / URI to play the song?
Thanks in advance and thank you for your hard work for this awesome library!
