### ISSUE TITLE
Why is it so hard to add a track?

### ISSUE THREAD

**Issue by matrixfox** [thelinmichael/spotify-web-api-node#141]
I can't even add a simple track to a playlist using the examples... Why is this so hard?

**Comment by amarcher** [comment]
With a [recent change](https://github.com/thelinmichael/spotify-web-api-node/pull/117/files) it looks like `trackIds` now must be an Array where previously you could provide a String.

To make matters worse (at least in my case), I found that my client was coercing single member arrays (e.g. `['spotify:track:5iKoarDSV0EA1JN10Bljr5']`) into strings (e.g. `spotify:track:5iKoarDSV0EA1JN10Bljr5`) when embedding them in the `FormData` of a post to my node server.

I resolved my issues by coercing the trackIds into an Array on the server-side:

	let trackIds = req.body.trackIds;
	if (trackIds && !Array.isArray(trackIds)) {
		trackIds = trackIds.split(',');
	}

**Comment by JMPerez** [comment]
Closing the ticket since this is not an issue in the wrapper. Thanks @amarcher for documenting the workaround!
