### ISSUE TITLE
server methods not merged into web api

### ISSUE THREAD

**Issue by rmmjohann** [thelinmichael/spotify-web-api-node#142]
I try to use this wrapper in a ES6 react app with webpack by importing like this:
```javascript
const spotifyApi = new SpotifyWebApi({
  clientId : '...',
  clientSecret : '...'
})

spotifyApi.clientCredentialsGrant()
  .then(function(data) {
    console.log('The access token expires in ' + data.body['expires_in']);
    console.log('The access token is ' + data.body['access_token']);

    // Save the access token so that it's used in future calls
    spotifyApi.setAccessToken(data.body['access_token']);
  }, function(err) {
    console.log('Something went wrong when retrieving an access token', err);
  });
```

The result is an error that `spotifyApi` has no method `clientCredentialsGrant`.

Even patching the server methods manually into the api via
```javascript
const spotifyApi = Object.assign(new SpotifyWebApi({
  clientId : 'cb3b28cb5f8a4e1e852e523eea4b89c4',
  clientSecret : '7f7421f6b9f34745b93222b9387a83e0'
}), SpotifyWebApiServerMethods)
```
it won't work, because the call to spotify web api is just an OPTION request.

Am I missing something/doing some thing wrong?

**Comment by rmmjohann** [comment]
There's a german saying "Those who can read have clearly an advantage".
Didn't read through the initial README where it is stated that client credential authentication won't be supported. It's obvious that the chrome dev tools are displaying an OPTION request because of cross origin policy violation: Accept Origin header is not set because client credential authentication has to be done at the server...

Even though, can somebody explain why the server methods aren't accessible/defined when using this lib at the browser?

**Comment by jpiepkow** [comment]
Also I should say...you should ever have both your client secret on client side.

**Comment by jpiepkow** [comment]
Have your*

**Comment by JMPerez** [comment]
The reason why those methods aren't included in the browser bundle is covered in https://github.com/thelinmichael/spotify-web-api-node/issues/94#issuecomment-261291428
