### ISSUE TITLE
Access Token Needed

### ISSUE THREAD

**Issue by AnishGDev** [thelinmichael/spotify-web-api-node#144]
From May 29th, access tokens are needed for unauthenicated web api calls.
This includes:
```
/v1/search
/v1/tracks/{track_id}
/v1/tracks?ids={track_ids}
/v1/artists/{artist_id}
/v1/artists?ids={artist_ids}
/v1/artists/{artist_id}/albums
/v1/artists/{artist_id}/top-tracks
/v1/artists/{artist_id}/related-artists
/v1/albums/{album_id}
/v1/albums?ids={album_ids}
/v1/albums/{album_id}/tracks
/v1/users/{user_id}
```
Any idea how I could use this module, with the change? I'm kind of lost right now.

**Comment by eugenesia** [comment]
Hi, in May 2017, [Spotify disabled unauthenticated calls to the Web API](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/).

Now you need to get and set an access token, to be used in every call to search tracks, etc. The token needs to be set again after it expires in 3600 seconds (1 hour). See example code:

```javascript
const spotifyApi = new SpotifyWebApi({
  clientId: 'myClientId',
  clientSecret: 'myClientSecret',
  redirectUri: 'myRedirectUri',
});

// Set an access token.
// This is required as Spotify implemented a new auth flow since May 2017.
// See https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/
spotifyApi.clientCredentialsGrant()
  .then(function(data) {
    console.log('The access token expires in ' + data.body['expires_in']);
    console.log('The access token is ' + data.body['access_token']);

    // Save the access token so that it's used in future calls
    spotifyApi.setAccessToken(data.body['access_token']);
  }, function(err) {
    console.log('Something went wrong when retrieving an access token', err.message);
  });
```

**Comment by breakpoint25** [comment]
I wish Spotify and others would update documentation for this.

But you just need to 

- sign up with a developer account
- create an app 
- copy the tokens to the appropriate place in the example

https://developer.spotify.com/my-applications/#!/applications

var spotifyApi = new SpotifyWebApi({
  clientId : 'fcecfc72172e4cd267473117a17cbd4d',
  clientSecret : 'a6338157c9bb5ac9c71924cb2940e1a7',
  redirectUri : 'http://www.example.com/callback'
});

**Comment by JMPerez** [comment]
Closing this issue since there is no change to be made in the library.
