### ISSUE TITLE
TypeError: albumIds.join is not a function

### ISSUE THREAD

**Issue by OGNova** [thelinmichael/spotify-web-api-node#164]
I'm attempting to use the package within a command that utilizes the Discord API and the package Discord.js, and when attempting to grab an albums information from a command via Discord, I get this [error](https://hastebin.com/uvapitequm.rb). The code for the command which is attempting to use this package can be found [here](https://hastebin.com/qodemisoju.js). Any help with this would be much appreciated.

**Comment by brodin** [comment]
`getAlbums` is expecting an array of ids (eg. `['41MnTivkwTO3UUJ8DrqEJJ']`), I don't see your code verifying this? Example here https://github.com/thelinmichael/spotify-web-api-node/blob/fa60a5921fb8088a4023794b08b27cc741acbd4e/test/spotify-web-api.js#L300

**Comment by brodin** [comment]
Your authorization is incomplete – see https://github.com/thelinmichael/spotify-web-api-node#client-credential-flow for reference.

**Comment by brodin** [comment]
@OGNova did this solve your problems?

**Comment by JMPerez** [comment]
Closing this issue. Feel free to reopen if this is still a problem.
