### ISSUE TITLE
getMe() gives 401 error

### ISSUE THREAD

**Issue by QuadDepo** [thelinmichael/spotify-web-api-node#166]
I'm trying to get the (me) the user using this script.

`		spotifyApi.clientCredentialsGrant()
		  .then(function(data) {
		    console.log('The access token expires in ' + data.body['expires_in']);
		    console.log('The access token is ' + data.body['access_token']);

		    // Save the access token so that it's used in future calls
		    spotifyApi.setAccessToken(data.body['access_token']);
				spotifyApi.getMe()
				  .then(function(data) {
				    console.log('Some information about the authenticated user', data.body);
				  }, function(err) {
				    console.log('Something went wrong!', err);
				  });
		  }, function(err) {
		        console.log('Something went wrong when retrieving an access token', err);
		  });`

This is the response

`
The access token expires in 3600
The access token is *****************************************
Something went wrong! { [WebapiError: Unauthorized] name: 'WebapiError', message: 'Unauthorized', statusCode: 401 }
`

Any idea?

**Comment by alvaizq** [comment]
I have the same problem. Any idea??

**Comment by QuadDepo** [comment]
It has something to do with the type of auth your using.

**Comment by JMPerez** [comment]
@QuadDepo could you fix this issue?

**Comment by QuadDepo** [comment]
@JMPerez The problem was that i was using an other typ of auth.

**Comment by JMPerez** [comment]
@QuadDepo 👍 

I'll close the ticket then.

**Comment by piyushsingh0992** [comment]
I am tring to set the user but it's working even the dispatch is not getting triggered; 

 spotify.getMe().then((user) => {
        console.log('it entered2');
        dispatch({
          type: "SET_USER",
          user:user,
        });
      });
