### ISSUE TITLE
Play - Not possible to select device_id

### ISSUE THREAD

**Issue by zjeel** [thelinmichael/spotify-web-api-node#170]
It should be possible to select the device_id to play.
Which is not feasible for the moment with this library.
Can you adapt this, so we can add also URL params (device_id next to Body params (options))
->https://beta.developer.spotify.com/console/put-play/

Thanks for this amazing library! :)

**Comment by Jean-PhilippeD** [comment]
I've just tested the dirty way by adding the query device_id on the play endpoint and it works fine.
I hope this features willbe supported asap too :)

**Comment by bluepuma77** [comment]
+1 Would be great to have this basic function in the next release

**Comment by JMPerez** [comment]
I'm happy to inform that this has been implemented and shipped in version 3.0.0.
