### ISSUE TITLE
Find music by theme

### ISSUE THREAD

**Issue by voold** [thelinmichael/spotify-web-api-node#172]
If i want to listen for some rock music, is there a promise that enables us to return a list of song linked to rock music for example?

Best

**Comment by brodin** [comment]
https://developer.spotify.com/web-api/search-item/

**Comment by brodin** [comment]
Did this solve your problem @voold?

**Comment by JMPerez** [comment]
There is basic support for searching by genres in Spotify's Web API, searching for `genre:<your_genre>`. Check the docs on https://developer.spotify.com/web-api/search-item/ and an example on https://developer.spotify.com/web-api/console/get-search-item/?q=genre%3Arock&type=track.
