### ISSUE TITLE
using variables in wrapper requests

### ISSUE THREAD

**Issue by thedjfresh** [thelinmichael/spotify-web-api-node#174]
Hey

JMPerez kindly forwarded me here .. thanks!
Having issues concanting an array into the wrapped request for add to playlist

` spotifyApi.addTracksToPlaylist('iluvdrumandbass', '1UG26LaMkbdgFvsi430fW1', JSON.stringify(finalUri))`

gives me
{name: "WebapiError", message: "Bad Request", statusCode: 400}

(Authentication is working fine)
I have tried both 
` spotifyApi.addTracksToPlaylist('iluvdrumandbass', '1UG26LaMkbdgFvsi430fW1', JSON.stringify(finalUri))`
and
` spotifyApi.addTracksToPlaylist('iluvdrumandbass', '1UG26LaMkbdgFvsi430fW1', finalUri)`

where **finalUri** is
`["spotify:track:0D5zFzZDG2vFzmizPBoq9I","spotify:track:1wY2yIk3UtwLFZPcQgyejq","spotify:track:3KjskT7nZJT3bNF2eLelnh"]`

or technically `finalUri='["spotify:track:0D5zFzZDG2vFzmizPBoq9I","spotify:track:1wY2yIk3UtwLFZPcQgyejq","spotify:track:3KjskT7nZJT3bNF2eLelnh"]'`

This is definetely not my favourite part of JS!

Haven't been able to find anything in the notes here to explain how to use variables as part of a request

Thanks

Dan

**Comment by onhernandes** [comment]
Days ago I sent an array then it worked, but I was just testing and now I just need this working for finish my project, but this isn't working too :( I'm sending an array containing the musics' URIs.

**Comment by onhernandes** [comment]
Ok, wrongly I was sending the album's URI, not the track's URI. My mistake. But I used these tracks you provided and they worked nicely here. Did you check your scopes and if the access token is valid?
Also, you must pass an array containing the URIs instead a string

**Comment by thedjfresh** [comment]
Its not a token issue. I get different errors when it is. Im testing with a full scope querystring grabbed from working client side version of same app.

The URI still needs to be in brackets though? ([]) ... are you saying passing an array like that is working for you?

**Comment by onhernandes** [comment]
Yes, I'm passing an array with URIs like `['uri','uri']` and its working right now. What about your playlist's ID? Use the endpoint for getting the playlist and confirm..besides that, I don't know more :/

**Comment by thedjfresh** [comment]
I checked
`["spotify:track:0D5zFzZDG2vFzmizPBoq9I", "spotify:track:1wY2yIk3UtwLFZPcQgyejq", "spotify:track:3KjskT7nZJT3bNF2eLelnh"]`
This is my debugger logging the value of the Array (idArray), ive checked with Array.IsArray (which returns true)

This is all the related code

```
  var SpotifyWebApi = require('spotify-web-api-node');
    var spotifyApi = new SpotifyWebApi();
spotifyApi.setAccessToken('BQAP08ZqAjlifhFXh9W2DKKJny_usWZB552SmnFGODvKZXUCIKo3TdLpxsEoMxCD_r2gB-dj3T4UO8dIp48RwzTjf9x3MaViU6fyVAGRZuzNxAgSuJS-np11VnNz1gc5bwRB3lxjNZ2qCyMZCXhQHvuDHgYrsWXvWz5w&refresh_token=AQB-Ja7XxNRILRqaqWFfcWIul4srjSJZbxkcu1O2o-e8kLyJOlHD1tM8Kt19eWc3u8s8ksSxRR3itI36ouStSVRsKf5B3o0nED9f7SSmamnh2vQOl60WelEZx4Ib7HgxPnQ');

  spotifyApi.addTracksToPlaylist('iluvdrumandbass', '1UG26LaMkbdgFvsi430fW1', idArray) .then(function (data) {
      console.log('Added tracks to playlist!');
    }, function (err) {
      console.log('Something went wrong!', err);
    });

```
The access token was valid when i checked and im getting back:
WebapiError {name: "WebapiError", message: "Forbidden", statusCode: 403}

**Comment by thedjfresh** [comment]
Fixed this.. was a dumb mistake i was grabbing token with wrong scopes saved in an old node file! eeek sorry. Thanks onhernandes!

**Comment by onhernandes** [comment]
Great! You're welcome :D
