### ISSUE TITLE
What does local and country mean?

### ISSUE THREAD

**Issue by Tzikas** [thelinmichael/spotify-web-api-node#180]
I'm trying to query music from a certain country or locale.  What do these options mean in your methods.  I looked at https://developer.spotify.com/web-api/endpoint-reference/  to try to see if they're included in the spotify docs but couldn't find it.  Thanks a lot !

**Comment by Tzikas** [comment]
I see it here https://beta.developer.spotify.com/documentation/web-api/reference/browse/get-list-featured-playlists/ , but the results don't seem to always correctly reflect

**Comment by JMPerez** [comment]
Hi @Tzikas! We are passing the options supported by Spotify Web API. If you have any questions around the actual data returned you can use Spotify's issue tracker on https://github.com/spotify/web-api/issues.
