### ISSUE TITLE
searchArtists argument must be exact.

### ISSUE THREAD

**Issue by NicBonetto** [thelinmichael/spotify-web-api-node#186]
Is there a way to change the searchArtists method so you do not have to pass in the exact string to search for the desired artist? For example, this will return no results:

`...searchArtists('kanye west')...`

However, this will:

`..searchArtists('Kanye West')...`

When I implement this method, I am taking the search query from user input and sending the value to the method. I want the search query to be flexible so you do not have to search with exact spelling.

**Comment by JMPerez** [comment]
This doesn't seem to be the case for me. I do get results back when searching for `'kanye west'`. @NicBonetto could you double-check?

**Comment by JMPerez** [comment]
To keep things clean I will close this for now. Feel free to reopen if you can reproduce it.
