### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by crazydev71** [thelinmichael/spotify-web-api-node#188]
I am not able to call spotifyApi functions. Maybe missing typings I think.
Need help with this urgently
Thanks in advance

**Comment by zachberger** [comment]
This works fine in TypeScript... 

```typescript
import { SpotifyWebApi } from "spotify-web-api-node";

const spotify = new SpotifyWebApi();
const searchResult = spotify.searchArtists('Pete Tong');
```

**Comment by JMPerez** [comment]
I will change this issue title so it shows that this is a feature request rather than a bug.

**Comment by ARoundSquare** [comment]
Was poking around in the referenced issues; this one can probably be closed since [this](https://www.npmjs.com/package/@types/spotify-web-api-node) was published?

**Comment by JMPerez** [comment]
@ARoundSquare thanks for cleaning up. I'll close the issue.

**Comment by thibleroy** [comment]
Can we access the interaces too ? I am currently not able to do this with ts v3.8

**Comment by nimobeeren** [comment]
@thibleroy the interfaces are not exported from the type definition file. That's a shame, I would like to use them too.

**Comment by thibleroy** [comment]
> @thibleroy the interfaces are not exported from the type definition file. That's a shame, I would like to use them too.

I can access the interfaces by the namespace SpotifyApi

**Comment by nimobeeren** [comment]
@thibleroy Thanks! Indeed I can access interfaces such as `SpotifyApi.TrackObjectFull` without importing anything else!
