### ISSUE TITLE
createPlaylist is missing the options parameter

### ISSUE THREAD

**Issue by allinallin** [thelinmichael/spotify-web-api-node#19]
`this.createPlaylist = function(userId, playlistName, callback) {...}`

Needed for setting `public` as demonstrated in the examples.

**Comment by thelinmichael** [comment]
Thanks for raising this @allinallin, I'll have it sorted shortly.

**Comment by thelinmichael** [comment]
Fixed and deployed in 1.3.5. Thanks again!
