### ISSUE TITLE
addToMySavedTracks returns status Bad Request 400 

### ISSUE THREAD

**Issue by yanniz0r** [thelinmichael/spotify-web-api-node#193]
Hey folks,

first of all: great project! Thank you for providing this simple and well documented library. However, I ran into an error when I tried adding a song to a users library with the function `addToMySavedTracks`. This function returns a Bad Request 400 response. I tried out your example from the documentation: 
```javascript
spotifyApi.addToMySavedTracks(["3VNWq8rTnQG6fM1eldSpZ0"])
```
I figured out, that this issue is happening due to a wrong use of the spotify web api (maybe it changed in the past - I haven't found any information about this). The [docs](https://beta.developer.spotify.com/documentation/web-api/reference/library/save-tracks-user/) say, that we need an request body of the following format: 
```javascript
{
  ids: ["4iV5W9uYEdYUVa79Axb7Rh", "1301WleyT98MSxVHPZCA6M"]
}
```
This is currently handled by the method call `.withBodyParameters(trackIds)` which results in a body with a single array. Changing the method call to `.withBodyParameters({  ids: trackIds })` solved the issue for me. 

I will provide a merge request today - I think the change will resolve this issue :)

**Comment by adcar** [comment]
Seems like this issue happens with all the addTo and removeFrom tracks / albums methods.

**Comment by JMPerez** [comment]
The API seems to support the format without `{ids: <list>}`, just passing the array. However, to be consistent with the docs we should add the key.
