### ISSUE TITLE
limit and offset dose not work with getPlaylist

### ISSUE THREAD

**Issue by claytja** [thelinmichael/spotify-web-api-node#198]
spotifyApi.getPlaylist(parsed.user, parsed.id,{ limit : 100, offset : 100 })
    .then(function(data) {
    
}, function(err) {
    return console.log('Something went wrong!', err);
});
will still print the first 100 songs.

**Comment by JMPerez** [comment]
@claytja The options supported for the get playlist endpoint are `fields` and `market` (see [documentation page](https://beta.developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/)).

If you want to paginate through the tracks you need to use the `getPlaylistTracks()` function.
