### ISSUE TITLE
Don't encode the colons separating the query fields in searchTracks()

### ISSUE THREAD

**Issue by jitowix** [thelinmichael/spotify-web-api-node#20]
As we can see in the api docs, we should not encode the colons which separate the query fields (artist, track, album etc)
https://developer.spotify.com/web-api/search-item/

The `searchTracks()` example from the main page call this url (with `'artist:Love'`)
`https://api.spotify.com/v1/search?query=artist%3ALove&offset=0&limit=20&type=track`
It should be `https://api.spotify.com/v1/search?query=artist:Love&offset=0&limit=20&type=track` 

Otherwise the returned results aren't correct.

**Comment by jitowix** [comment]
Sorry, looks like I was wrong...

**Comment by thelinmichael** [comment]
That's OK @jitowix, let me know if there's anything else.
