### ISSUE TITLE
/v1/me/playlists status:502

### ISSUE THREAD

**Issue by xingx2050** [thelinmichael/spotify-web-api-node#208]
request /v1/me/playlists  
{
  "error": {
    "status": 502,
    "message": "Backend respond with 500"
  }
}

The Spotify user ID is a number. Is the request failed related to the user ID?

**Comment by JMPerez** [comment]
Status code 502 is a server-error. This is a problem in Spotify's service, not this library.

If you can reproduce it with a short example you should file a ticket on https://github.com/spotify/web-api/issues
