### ISSUE TITLE
Unauthorized 401 error when using .getPlaylist ??? 

### ISSUE THREAD

**Issue by chasejh** [thelinmichael/spotify-web-api-node#209]
I got my authorization token -- but I am unable to actually use the API with the set token...  
When I do this on the web console I am able to view the JSON with this input.

I am not getting an error when I set the token. Just a 401 when using it.  

The example in the documentation I am pretty sure is wrong -- but after trying to use this method using my spotifyApi object I get a 401 error.  
This leads me to believe that the token is not being properly set.  
How should the token look? Also -- am I correct about the documentation for using .getPlaylistTracks being incorrect or am I misunderstanding how to use it?  #

My code   

```javascript
//get the first 5 playlist tracks
spotifyApi.getPlaylistTracks('12101400232',` '7E9lJfbhhjJIInarD6vLoN', {
    offset: 1,
    limit: 5,
    fields: 'items'
  })
  .then(
    function(data) {
      console.log('The playlist contains these tracks', data.body);
    },
    function(err) {
      console.log('Something went wrong!', err);
    }
  );
```

I get a 401 error.

Please help me!!

**Comment by JMPerez** [comment]
@chasejh did you manage to fix it? what was the cause?
