### ISSUE TITLE
Expose missing methods for removing tracks from playlists

### ISSUE THREAD

**Issue by JMPerez** [thelinmichael/spotify-web-api-node#22]
There are 2 uses of the "[Remove tracks from a playlist](https://developer.spotify.com/web-api/remove-tracks-playlist/)" endpoint that are not covered by the wrapper:

- Removing a specific occurrence of a track
- Removing the track at a given position in a specific playlist snapshot

**Comment by thelinmichael** [comment]
Added in 1.3.12! 

![](http://i.imgur.com/VhlQK.gif)
