### ISSUE TITLE
Debugging bad requests?

### ISSUE THREAD

**Issue by soccermitchy** [thelinmichael/spotify-web-api-node#220]
Whenever I call `spotifyApi.addTracksToPlaylist('someUserId', 'somePlaylistId', ['someTrackSpotifyUri'], function(ret) { console.log(ret) })`, I get a `WebApiError` with the message set to `Bad Request`. How would I debug this and figure out what is causing it? I can't even wireshark it because, well, it uses SSL.

**Comment by JMPerez** [comment]
You would need to edit the library in your `node_modules` and print what URL is being called and with what parameters. Maybe you can replace those ids and uris with the real values you are sending and paste it here so it's easier to debug.

**Comment by JMPerez** [comment]
I'm closing the ticket for now then
