### ISSUE TITLE
Receiving 400 Bad Request When using Get Followed Artists

### ISSUE THREAD

**Issue by lbrodie11** [thelinmichael/spotify-web-api-node#222]
Hi I've been struggling with this issue of calling getFollowedArtists() and I'm not sure what I'm doing incorrectly. I'm creating an app that periodically grabs artists new releases based on artists I personally follow with my Spotify account. Users will not be using my app so I'm trying to automatically authenticate my personal Spotify login credentials. My oath token works properly with the Spotify API Console, Postman and the curl command. I've been testing this in my terminal using the ```yargs``` module by calling the function and receive the following output
```Get Followed Artists has an issue! { [WebapiError: Bad Request] name: 'WebapiError', message: 'Bad Request', statusCode: 400 }```

My app can't seem to get past the ```spotifyApi.authorizationCodeGrant(code)``` step.

Any help would be greatly appreciated :)

```
var SpotifyWebApi = require('spotify-web-api-node');

var code = process.env.CODE;

var spotifyApi = new SpotifyWebApi({
  clientId: '5e1e2cc3a0dd422eb11244d00e3bb9a1',
  clientSecret: process.env.CLIENT_SECRET,
  redirectUri: 'https://example.com' //App website
});

export function request() {
  console.log('Authenticating Code***************')
  console.log(process.env.CLIENT_SECRET);
  console.log(process.env.CODE);
  console.log('Authorization Url******************')
  var authorizeURL = spotifyApi.createAuthorizeURL(scopes, state, false);

  spotifyApi.authorizationCodeGrant(code)

    .then(function (data) {
      spotifyApi.setAccessToken(data.body['access_token']);

      return spotifyApi.getFollowedArtists();
    })
    .then(function (artists) {
      console.log('This user is following ', artists.body.artists.total, ' artists!');
      console.log(artists.body.albums.items[0].id);

      var artistId = artists.body.albums.items[0].id;
      return artistId;

    }, function (err) {
      console.log("Get Followed Artists has an issue!", err);
    });
}
```
```
const argv = yargs
    .command(
        'get',
        'Get followed artists',
        {
            get: {
                type: 'boolean',
                description: 'gets artists you follow'
            }
        },
        async ({ get }) => {
            await request();
        }
    )
    .option('debug', { type: 'boolean', description: 'Set debug log level' })
    .help().argv;
```

The command I use call the function
```node . get```

FYI I've tested the getAlbumReleases method that works properly. I seem to have issues with the methods that have a specific required scope. I've also tried using ```authorizationCodeGrant``` vs ```clientCredentialsGrant``` and neither work.

**Comment by JMPerez** [comment]
This seems to work for me. What I did was to go to https://developer.spotify.com/console/get-following/?type=artist, get a token with the 'user-follow-read' scope, fill with sample data and try out. That showed the results on Spotify's console.

Then I wrote a code snippet like this:

```js
var spotifyApi = new SpotifyWebApi();
spotifyApi.setAccessToken('<here_the_access_token>');
spotifyApi.getFollowedArtists().then(
  function(data) {
    console.log(data);
  },
  function(err) {
    console.log('Something went wrong..', err.message);
  }
);
```

and got the expected response:

```js
{ body:
   { artists:
      { items: [Array],
        next: 'https://api.spotify.com/v1/me/following?type=artist&after=1AaN24tRzIpDKK54IRtdIe&limit=20',
        total: 127,
        cursors: [Object],
        limit: 20,
        href: 'https://api.spotify.com/v1/me/following?type=artist&limit=20' } },
  headers:
   { 'content-type': 'application/json; charset=utf-8',...
```

Try with those steps to figure out if there is an issue on Spotify's end or in the library.

**Comment by lbrodie11** [comment]
Thank you @JMPerez ! I made it much harder than I needed to. For my  usage it seems like I didn't need to do all that extra setup. Works perfectly by just adding the access token! I really appreciate the help.

**Comment by JMPerez** [comment]
@lbrodie11 Since the endpoint you are consuming returns user's personal data, you need user's permission, and that means showing the login form. Good news is that you can use the [Authorization Code flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow).

In this flow you get a refresh token that you can use to obtain new access tokens when these expire. You will be able to fetch tokens as long as the user doesn't change passwords, revokes your app permissions or any other corner case.

I'm closing this issue since it seems to be already solved.
