### ISSUE TITLE
Problem with getUserPlaylists parameters

### ISSUE THREAD

**Issue by ivsm** [thelinmichael/spotify-web-api-node#226]
Hello, I am using this wrapper for NodeJS. I have a question about the getUserPlaylists method and its parameters. I want to specify the limit and the offset and I don't know how to specify them because it is not clear in the docs. 
I did it like this but it doesn't work. 
`spotifyApi.getUserPlaylists({limit: 27, offset: 7})
        .then(function(data) {`

**Comment by JMPerez** [comment]
Use `getUserPlaylists` to fetch a certain user's playlists. You need to pass the userId as the first parameter. See https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/spotify-web-api.js#L445-L455 for more information.

There is another endpoint to [fetch the current user's playlists](https://developer.spotify.com/documentation/web-api/reference/playlists/get-a-list-of-current-users-playlists/) that doesn't need an explicit userId, but it's not implemented in this library yet.

**Comment by ivsm** [comment]
That's not what I was asking, but thanks. getUserPlaylists does not need the userId and in that case, it will fetch the playlist of the user that is logged in. I want to know info about the parameters of getUserPlaylists and how to specify them. I did it like I specified it in the question but it doesn't work. In the link that you wrote for more information it is stated that it can have an object with options as parameters but I don't know how to write it. Can you help me with that? Because, in my opinion it is not well explained in the docs.

**Comment by JMPerez** [comment]
True, my fault. I should have read the documentation of the function better.
The options that you can pass are the ones that [the endpoint supports](https://developer.spotify.com/documentation/web-api/reference/playlists/get-list-users-playlists/), which are `limit` and `offset`.

The problem is that there is a bug in the implementation. When the `userId` is not provided it should set `options` to the first parameter of the function, which it doesn't do. A workaround for now is to pass `null` as the `userId`:

```js
spotifyApi.getUserPlaylists(null, {limit: 27, offset: 7}).then(function(data) {
```

Let me know if that solves it and I'll file a ticket to fix this.

**Comment by ivsm** [comment]
Yes, that solves it! Thank you very much! Muchas gracias (también soy español) :)

**Comment by JMPerez** [comment]
¡Me alegro de que haya funcionado!

**Comment by piyushsingh0992** [comment]
spotifyApi
  .getUserPlaylists()  is returning an empty item list  how to solve that ?

**Comment by hirensavani-99** [comment]
@piyushsingh0992  i am getting same problem if you have solved the problem can you help me?

**Comment by jsears** [comment]
This is not working for me.  Consistently returns:
WebapiRegularError: An error occurred while communicating with Spotify's Web API.

Has the methodology for this changed?

ETA: nm, distregard, error was limit being set was not valid.  But I couldn't see the actual error, would be nice.  Cheers.
