### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by buitro666** [thelinmichael/spotify-web-api-node#228]
Hello, I'm trying to create a small app that is capable of retrieving the current playing track for the logged user. However, I think I don't fully understand the whole authentication and authorization process, since I keep getting 401 errcode when trying to get the playback state. The code I'm using is as follows:

```js
var SpotifyWebApi = require('spotify-web-api-node'),
  spotifyApi = new SpotifyWebApi({
    redirectUri: 'https://google.com',
    clientId: '',
    clientSecret: ''
  }),
  scopes = ['user-read-currently-playing'];

var code = '';

spotifyApi
  .authorizationCodeGrant(code)
  .then(
    function(data) {
      console.log('The access token is ' + data.body['access_token']);
      console.log('The refresh token is ' + data.body['refresh_token']);
      spotifyApi.setAccessToken(data.body['access_token']);
      spotifyApi.setRefreshToken(data.body['refresh_token']);
    },
    function(err) {
      console.log('Something went wrong', err);
    }
  )
  .then(
    spotifyApi.getMyCurrentPlaybackState({}).then(
      function(data) {
        console.log('Now Playing: ', data.body);
      },
      function(err) {
        console.log('Something went wrong!', err);
      }
    )
  );
```

As I don't have a website yet, and obtaining the auth code from a GET request via Express localhost didn't work for me, I'm currently hardcoding it. Also I'm kinda confused, since the output throws the 401 error before providing the tokens via console. Maybe it's just some silly mistake. As I said, I don't really understand the way all this process works, and I'm currently not very keen on Node, either.

Any help would be appreciated. Thank you in advance!

(EDIT: the code and the client credentials are censored for obvious reasons, but I always double-check them and I don't think the problem comes from there)

**Comment by JMPerez** [comment]
@buitro666 I strongly recommend you to go through [Spotify's Web API tutorial](https://developer.spotify.com/documentation/web-api/quick-start/) and [authorization guide](https://developer.spotify.com/documentation/general/guides/authorization-guide/). The tutorial will show you how to create a web server in node to handle authentication and fetch user's data. Once you are familiar with the process you can use the node wrapper to replace some of the boilerplate code.

**Comment by buitro666** [comment]
Thank you very much, @JMPerez. I will let you know in case that I experience further trouble.

**Comment by JMPerez** [comment]
Closing the ticket
