### ISSUE TITLE
Authenticate in console?

### ISSUE THREAD

**Issue by mqmq0** [thelinmichael/spotify-web-api-node#232]
I'm trying to understand/implement the authentication process of this warper, but all the info I can find is assumes that I run the project on a browser or an app. 
Like this: https://stackoverflow.com/questions/27761493/using-spotify-web-api-node-to-generate-an-authentication-token

What if I want to authenticate my script in Linux terminal?
If I run this:
https://github.com/thelinmichael/spotify-web-api-node/blob/master/examples/access-token-using-client-credentials.js
I get "bad request" error. 
Can someone please point me to a working example of this kind of authentication?

**Comment by JMPerez** [comment]
@mqmq0 can you provide some code snippet with the code you are trying to run?
If you are trying to access endpoints that need user's authorization, then you need to implement the authorization code flow. This will give you a refresh token that you can use later on in your script to obtain access tokens without having to go through the login form.

**Comment by JMPerez** [comment]
I'm closing this issue. Feel free to reopen it if you have any further questions.
