### ISSUE TITLE
September Playlist API Updates

### ISSUE THREAD

**Issue by jmfortunatojr** [thelinmichael/spotify-web-api-node#234]
Reference: https://developer.spotify.com/community/news/2018/06/12/changes-to-playlist-uris/

Will this library be updated to be in compliance to with the new endpoints?

**Comment by MichaelKohler** [comment]
There is a PR here: https://github.com/thelinmichael/spotify-web-api-node/pull/235

**Comment by JMPerez** [comment]
Fixed on https://github.com/thelinmichael/spotify-web-api-node/pull/243
