### ISSUE TITLE
Search request is incorrect

### ISSUE THREAD

**Issue by MatthewStanciu** [thelinmichael/spotify-web-api-node#242]
I'm trying to use this API to search for a particular song belonging to a particular artist. It doesn't return the data (and neither does the code in the example). This is because the request is supposed to say "q=track{etc}" (as the Spotify documentation details) but instead it says "query=track{etc}". Running the same cURL request in my terminal returns the correct results with q but not with query. 
<img width="531" alt="screenshot 2018-09-11 23 55 48" src="https://user-images.githubusercontent.com/14811170/45401437-9e8b3f00-b61e-11e8-882f-6c0946860de8.png">

**Comment by JMPerez** [comment]
I'm getting the same results using `q` and using `query`:

```bash
curl -X "GET" "https://api.spotify.com/v1/search?q=track%3AAlright%20artist%3AKendrick%20Lamar&type=track&market=US&limit=20&offset=0" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer XXX"
```

```bash
curl -X "GET" "https://api.spotify.com/v1/search?query=track%3AAlright%20artist%3AKendrick%20Lamar&type=track&market=US&limit=20&offset=0" \
 -H "Accept: application/json" \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer XXX"
```

results in:

```js
{
  "tracks" : {
    "href" : "https://api.spotify.com/v1/search?query=track%3AAlright+artist%3AKendrick+Lamar&type=track&market=US&offset=0&limit=20",
    "items" : [ {
...
    "limit" : 20,
    "next" : null,
    "offset" : 0,
    "previous" : null,
    "total" : 4
  }
}
```

It might be good to change the parameter in the library so it matches the one that is documented on Spotify's developer site. In any case, double check if there is something else in your code preventing the version with `query` to return data.

**Comment by JMPerez** [comment]
By the way, I see that the library is using `q`(see https://github.com/thelinmichael/spotify-web-api-node/blob/2fcd60c30368255dab658b534b4229909ace5d43/src/spotify-web-api.js#L278). What version of the library are you running?

**Comment by MatthewStanciu** [comment]
Hmm, that's so weird... why does it not work when I make the request with "query"?
![image](https://user-images.githubusercontent.com/14811170/45423285-de731600-b660-11e8-994a-7b8ef1611fa3.png)
![image](https://user-images.githubusercontent.com/14811170/45423289-e29f3380-b660-11e8-98ee-d9dc7849e61c.png)

In the image I posted last night, the request made from the package was formatted as "query". I am running version 3.1.1... is there a newer version I somehow missed out on? This doesn't make sense.

**Comment by JMPerez** [comment]
Can you paste the code you are executing where you call the `search()` function from this library?

**Comment by MatthewStanciu** [comment]
The code I am using is the same as what the example in the README uses, except I substitute the Kendrick Lamar track for a track submitted in a form.

```javascript
app.post('/song', function(req, res) {
  var track = (req.body.submiturl);
  var artist = (req.body.submitartist);
  spotify.searchTracks('track:'+track+ ' artist:'+ artist)
  .then(function(data) {
    console.log(data.body);
  }, function(err) {
    console.log('Something went wrong!', err);
  });
})
```

**Comment by MatthewStanciu** [comment]
I fixed the issue by using JSON.stringify(data.body) instead of simple data.body. When I printed out simply `data.body`, it returned the tracks as [Object] [Object] [Object] instead of showing its actual contents. Perhaps the documentation should be updated to reflect this?

**Comment by MatthewStanciu** [comment]
Here's my full search code for anyone else who might have the same issue in the future. You can also check out the [full repository](https://github.com/MatthewStanciu/HackClubPlaylist).

```javascript
    spotify.searchTracks('track:'+track+ ' artist:'+ artist)
    .then(function(data) {
      var uri = JSON.stringify(data.body['tracks']['items'][0]['uri']);
      post(uri);
      console.log("added " + track + " by " + artist +" to the playlist!");
    }, function(err) {
      console.log(err);
    })
```
