### ISSUE TITLE
authorizationCodeGrant

### ISSUE THREAD

**Issue by irene-hakes** [thelinmichael/spotify-web-api-node#251]
First off, thank you so much for building this library!
I am trying to integrate this in a small project I am working on and was following the notes provided. To retreive my access token and refresh token, it suggested using spotifyApi.authorizationCodeGrant once I receive my code. The current npm package doesn't seem to have that method any more. Is there a new way to do this?

**Comment by jayheavner** [comment]
I noticed the same. Did you ever solve your problem?
