### ISSUE TITLE
Requests to play a track return 400 and 401 after refreshing access token

### ISSUE THREAD

**Issue by satyasinha94** [thelinmichael/spotify-web-api-node#267]
I have a setInterval running to refresh my access token every 30 minutes or so, but after the original token expires. I get a 400 error where the message is "Invalid track uri in payload". Double clicking on this from the network tab of chrome devtools shows a different error: "401: No token provided".  I have the token in localstorage, and have confirmed it's being replaced with new tokens with console.logs, so I'm stumped here frankly.

**Comment by kyds3k** [comment]
@satyasinha94 - how did you fix this? I'm having a similar problem . . .
