### ISSUE TITLE
Application flow

### ISSUE THREAD

**Issue by mikefrancis** [thelinmichael/spotify-web-api-node#27]
Apologies if this sounds like a stupid question, but how would I use access/refresh tokens in my app to authenticate a user or send a user to the authorise URL?

https://github.com/benchmarkstudios/slackbox/blob/master/app.js

If I run `auth()` instead of `findTrack('track')` on initialisation (Line 42), I get an authorisation URL in the console, which in turns gives me a `code`. If I paste this in to Line 9 and re-run - then the app works as needed.

However, if I try and run this _again_, obviously `code` becomes invalid and I have to repeat the process again, which isn't ideal, so I'm just wondering where I might be going wrong?

Any help appreciated!

**Comment by JMPerez** [comment]
Your redirectUri should process that code and exchange it with an access token, in a similar way as https://github.com/spotify/web-api-auth-examples/blob/master/authorization_code/app.js#L74 does it

What's the value of your redirectUri?

**Comment by thelinmichael** [comment]
To add to @JMPerez response - The code to access token exchange can be done using the `authorizationCodeGrant(authorizationCode)` method, see https://github.com/thelinmichael/spotify-web-api-node/blob/master/examples/access-token-refresh.js#L31 for an example.

**Comment by mikefrancis** [comment]
Thanks for your responses; will take a look and get back to you.

**Comment by mikefrancis** [comment]
Working fine now, thanks again.
