### ISSUE TITLE
404 WebApi Error: Not Found when attempting to create a playlist

### ISSUE THREAD

**Issue by Helguera** [thelinmichael/spotify-web-api-node#273]
Hi,

I am trying to create a playlist with the example I found in your GitHub, but it tells me:

`Something went wrong! { [WebapiError: Not Found] name: 'WebapiError', message: 'Not Found', statusCode: 404 }`

Any help would be appreciated. Thanks!

**Comment by Helguera** [comment]
I fixed it. It is important to add the username:

```
spotifyApi.createPlaylist('USERNAME', 'My Cool Playlist', { 'public': true })
        .then(function (data) {
          console.log('Created playlist!');
        }, function (err) {
          console.log('Something went wrong!', err);
        });
```

And also add this to the scope:
`playlist-modify-public` and `playlist-modify-private`

**Comment by andrewpat24** [comment]
Thanks, experienced this exact same issue. 

Can't believe I missed this, thanks a ton!!
