### ISSUE TITLE
No way to fetch list of private playlists?

### ISSUE THREAD

**Issue by notoriousturtle** [thelinmichael/spotify-web-api-node#274]

**Comment by kevinguebert** [comment]
I'm pretty sure `getUserPlaylists` should get a list of the private playlists: https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/spotify-web-api.js#L456

Do note, you have to make sure you have the required scopes outlined here: https://developer.spotify.com/documentation/web-api/reference/playlists/get-a-list-of-current-users-playlists/

**Comment by thelinmichael** [comment]
Exactly what @kevinguebert is saying - you need to have the required scope/permission.
