### ISSUE TITLE
Support for markets parameter

### ISSUE THREAD

**Issue by Christilut** [thelinmichael/spotify-web-api-node#279]
The search doesnt support the `markets` parameter right now, which makes it default to `US`. Sadly this is not properly documented by Spotify.
This is why non-English search queries give poor results.

The `markets` parameter should be added to all searches so we can change from `US` to anything we need.

**Comment by Christilut** [comment]
Okay, I thought I'd add it myself but there is actually support for it when I read the code. But it's not documented at all.

`searchTracks(query, { market: 'US' })`

**Comment by thelinmichael** [comment]
Great that you found it. It'll be more explicit in the new generated docs.

One important feature is to use `from_token` instead of a country code. It'll make Spotify use the market that's tied to the user who has granted the access token.
