### ISSUE TITLE
Authorization Code authentication error: "net::ERR_CONNECTION_REFUSED"

### ISSUE THREAD

**Issue by Woodhartt** [thelinmichael/spotify-web-api-node#280]
Hello,
I use your module on mobile to integrate Spotify into my application. At first, I used client credentials authentication but I would like to set up Authorization code authentication. I can create the authorization url with the createAuthorizeURL function, this one opens the page allowing the user to connect with his account but I have a problem with the redirection to the second page: the user's authorization to access data. It does not open and displays the error code: Encountered an error loading page', { description:'net::ERR_CONNECTION_REFUSED'.
I would like to know if you have any idea where this problem might come from and, more importantly, how to solve it.

Thank you in advance for your answer. Have a good day.

**Comment by SwapnilSoni1999** [comment]
check examples they have provided better code than startup code
