### ISSUE TITLE
WebApiError does not capture reason

### ISSUE THREAD

**Issue by thislooksfun** [thelinmichael/spotify-web-api-node#286]
When calling player endpoints (such as [play][play] or [pause][pause]), if an error occurs the web API returns a [player error object][error] which includes a `reason` string saying why the request failed. It would be incredibly useful if this information was passed on in the returned `WebApiError` object.

[play]: https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/
[pause]: https://developer.spotify.com/documentation/web-api/reference/player/pause-a-users-playback/
[error]: https://developer.spotify.com/documentation/web-api/reference/object-model/#player-error-object

**Comment by konstantinjdobler** [comment]
I agree, I needed this for an integration I am building. I opened a PR #294 to fix this.
