### ISSUE TITLE
The image size of artist is incorrect

### ISSUE THREAD

**Issue by jzhw0130** [thelinmichael/spotify-web-api-node#305]
Easy to replicate the issue by curl command as follows:

Issue found on Apr 24th 2020.

#### Endpoint(s):
* `GET /v1/artists/7heucQ89tyr0QHnwB4QO4j`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open terminal
2. run command :
```
curl -X "GET" "https://api.spotify.com/v1/artists/7heucQ89tyr0QHnwB4QO4j" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer xxxx"
```

#### Expected behaviour:
The ratio of all images is `1:1`, and the actual `width` and `height` of image is same.

#### Actual behaviour:
The ratio of all images is `1:1`, but the actual `width` and `height` of image is different.
For example, the first image size is : width(361) * height(640)
```
{
  "external_urls" : {
    "spotify" : "https://open.spotify.com/artist/7heucQ89tyr0QHnwB4QO4j"
  },
  "followers" : {
    "href" : null,
    "total" : 26
  },
  "genres" : [ ],
  "href" : "https://api.spotify.com/v1/artists/7heucQ89tyr0QHnwB4QO4j",
  "id" : "7heucQ89tyr0QHnwB4QO4j",
  "images" : [ {
    "height" : 640,
    "url" : "https://i.scdn.co/image/6456bbf9ddfb47b9ea40d1206d208013aa84d372",
    "width" : 640
  }, {
    "height" : 320,
    "url" : "https://i.scdn.co/image/142c8c7c2520663cfb7a1666a8098cf23003a389",
    "width" : 320
  }, {
    "height" : 160,
    "url" : "https://i.scdn.co/image/b8bcb2be4f5fa71ec7ce88659ca7452a543375eb",
    "width" : 160
  } ],
  "name" : "Dapper Spider and The Moth Man",
  "popularity" : 1,
  "type" : "artist",
  "uri" : "spotify:artist:7heucQ89tyr0QHnwB4QO4j"
}
```

**Comment by thelinmichael** [comment]
@jzhw0130, I can't see this issue in the response you posted. If it indeed is a bug, it doesn't look like it's related to this project. The scope of this repository is limited to a JS client using the web api.
