### ISSUE TITLE
authorizationCodeGrant not working.

### ISSUE THREAD

**Issue by Hugocaminada** [thelinmichael/spotify-web-api-node#312]
Hey, I have the following code on my firebase server for authenticating a user:

```
var SpotifyWebApi = require('spotify-web-api-node');

async function proxySpotifyToken(req, res){
    const spotifyApi = new SpotifyWebApi({
        clientId: "myId",
        clientSecret: "mySecret",
        redirectUri: "com.myRNapp:/callback",
    });

    const code = req.body.code;

    // console shows code
    console.log(code);

    if(code){
        spotifyApi.authorizationCodeGrant(code).then(
            data => {
                return res.json(data.body)
            },
            err => {
                console.log('Something went wrong!', err)
            }
        ).catch((oError) => {
            return res.json(oError)
        })
    }
}

module.exports = {
    authentication: proxySpotifyToken
};
```

I'm using react-native-app-auth to make the call to the server and pass on the code. As you can see, I'm logging the code in the Firebase console and it does shows a string, so that seems to be working.

Whatever I try, It always catches the following error:
Something went wrong! { [WebapiError: Bad Request] name: 'WebapiError', message: 'Bad Request', statusCode: 400 } 

Am i doing something wrong here?

**Comment by AquaWolf** [comment]
I'm also getting for authorizationCodeGrant the same Error "[Error [WebapiError]: Bad Request] { statusCode: 400 }".
Thought it is related that clientId and clientSecret were send in body.
According to Spotify Authorization Flow - Authorization Code - Spotify wants clientId and clientSecret as Base64 in the header. I tried already doing so in header but still getting the 400.

**Comment by AquaWolf** [comment]
Ok i dived a bit deeper and found that somehow i needed a codeverifier for the authorizationCodeGrant method. Here is the new method:
```
authorizationCodeGrant: function(code, code_verifier, callback) {
    return AuthenticationRequest.builder()
      .withPath('/api/token')
      .withBodyParameters({
        grant_type: 'authorization_code',
        redirect_uri: this.getRedirectURI(),
        code: code,
        code_verifier: code_verifier
      })
      .withHeaders({
        Authorization:
          'Basic ' +
          new Buffer(
            this.getClientId() + ':' + this.getClientSecret()
          ).toString('base64')
      })
      .build()
      .execute(HttpManager.post, callback);
  }
```

**Comment by Hugocaminada** [comment]
But should I then pass a code_verifier with the the function call? What does that look like?

I'm sorry, but I'm a bit new to this stuff.

**Comment by oliveroneill** [comment]
@AquaWolf Do you know where we should retrieve `code_verifier` from?

**Comment by AquaWolf** [comment]
Hmm you will need to implement Grant flow with PKCE. Currently I'm using AppAuth to get verifier from Spotify Auth endpoint. I'm sending verifier to my backend to get access token or refreshing it.

**Comment by oliveroneill** [comment]
Thanks @AquaWolf! Got it working

**Comment by Hugocaminada** [comment]
I just set the `usePKCE: false` in my react-native-app-auth config and the seems to do the trick! My issue didn't seem to be related to this package.
