### ISSUE TITLE
multiple albums or tracks is giving me unauthorized

### ISSUE THREAD

**Issue by ShivanshSharma1** [thelinmichael/spotify-web-api-node#325]
I am new to web development so if i am asking something stupid, sorry.
I authorized with the client credentials flow , when i am using
`
 url: 'https://api.spotify.com/v1/albums/3wCtCJ8O6SlGBWYfzAlsb2'
`
it is working but when i am using 
`
 url: 'https://api.spotify.com/v1/albums'
`
it is not working and giving me unauthorized

**Comment by thelinmichael** [comment]
Hi @ShivanshSharma1. Are you suppling the required album ids? Are you using this wrapper?

**Comment by thelinmichael** [comment]
Please re-open if the above wasn't your issue @ShivanshSharma1.
