### ISSUE TITLE
setAccessToken troubles

### ISSUE THREAD

**Issue by dgmolla** [thelinmichael/spotify-web-api-node#329]
![Screen Shot 2020-09-29 at 9 33 53 PM](https://user-images.githubusercontent.com/18452532/94636767-833e0b80-029b-11eb-99a7-ea65faaf284f.png)

Hi! I'm a fairly new programmer so apologies for any obvious questions haha. I'm trying to use getMyTopTracks; I'm able to grab an access token and pass it to setAccessToken, but am still getting a 401 error from getMyTopTracks. I've attached a pic of my code, any insight as to what could be going wrong?

Many thanks in advance

**Comment by thelinmichael** [comment]
Hi @dgmolla! Does your access token have the `user-top-read` scope? It's needed to retrieve that information and may explain the error.

**Comment by dgmolla** [comment]
Yes I've passed that in to the scopes object

**Comment by thelinmichael** [comment]
@dgmolla, it could be that your access token has expired. Try grabbing a new one and trying again.

**Comment by thelinmichael** [comment]
Closing this issue. Please reopen if this wasn't your issue @dgmolla.

**Comment by dgmolla** [comment]
Hey Michael, I got the request to work with plain Fetch without the wrapper but was never able to figure out why my setAccessToken wasn't working. Might have been something else in my code
