### ISSUE TITLE
Question: This package is last published 2 years ago but seems active. 

### ISSUE THREAD

**Issue by noudadrichem** [thelinmichael/spotify-web-api-node#332]
I'm fetching old code when installing via npm. Would love a fix.

**Comment by thelinmichael** [comment]
Appreciate the encouragement @noudadrichem - it's coming to npm shortly. Haven't been active in this repository for a long, long time, and I'm currently merging in all the PRs.

**Comment by noudadrichem** [comment]
Cool! Looking forward to it.
