### ISSUE TITLE
getEpisode()

### ISSUE THREAD

**Issue by randralph** [thelinmichael/spotify-web-api-node#335]
Hey,

Cool lib. Tried to use it to get meta info for episodes. I'm either missing something or it's not part of the lib yet?

Keep up the good work

**Comment by thelinmichael** [comment]
Hey @randralph! I'll release version 5 to npm shortly, and it'll support that endpoint.

**Comment by thelinmichael** [comment]
Just released this version to npm, so you should be good to go.
