### ISSUE TITLE
Documentation error for transferPlayback

### ISSUE THREAD

**Issue by Simber1** [thelinmichael/spotify-web-api-node#349]
The documentation for `spotifyApi.transferMyPlayback` makes no comment of needing to pass a "play" option in but the code will error out without one.

**Comment by thelinmichael** [comment]
@Simber1, you're absolutely right - the `options` parameter should be optional but currently isn't. I've fixed this locally and push a fix shortly. Thanks for raising it.

**Comment by Rajatkumar1510** [comment]
**bhdfs**
