### ISSUE TITLE
Discover Weekly

### ISSUE THREAD

**Issue by FinnanHolt** [thelinmichael/spotify-web-api-node#357]
Is there any way to get the Discover Weekly playlist?

`spotifyApi.getUserPlaylists(<userId>)` does not return it.

**Comment by thelinmichael** [comment]
Hi @FinnanHolt. I had to try this myself, and the endpoint does actually return the Discover Weekly playlist. (Try it yourself using the [API console](https://developer.spotify.com/console/get-current-user-playlists). One thing that might be unintuitive is that the owner of the playlist is the `spotify` user, and not the currently authenticated user. Hope this helps.

**Comment by FinnanHolt** [comment]
Hi there, thanks for taking the time to reply. 

It also works if you put your own username, however you must set your scopes to 'playlist-read-private'. Anyone else wanting to know how to do this can find the full code on my repo "DiscoverWeekly".
