### ISSUE TITLE
GetTracks API

### ISSUE THREAD

**Issue by camillo777** [thelinmichael/spotify-web-api-node#36]
Hi!
The GetTracks API should have an option to make the call with slices of 50 tracks (max) and give the result back.

**Comment by thelinmichael** [comment]
Hi @camillo777! Please elaborate on what you mean by "The GetTracks API". If you need to retrieve metadata for 50 tracks at once, you can actually do that using the [Get Several Tracks](https://developer.spotify.com/web-api/get-several-tracks/) endpoint.

**Comment by thelinmichael** [comment]
Hi @camillo777! A bit unsure of what you mean here. You can retrieve up to 50 tracks at a time by pushing track IDs into an array and passing that as the first argument to the `getTracks` method. What do you mean by slices?

**Comment by camillo777** [comment]
Yes the Spotify Web api limit seems 50.
But it seems there is no check in your wrapper for this to throw an error. 
It would be great if your wrapper could understand that the tracks in the request are more than 50 and make multiple requests under the hood and give back the correct number of results. 
Maybe it will take more time but will save users to avoid implement their own splitting and merging  mechanism. 
Just an idea to improve it.

**Comment by tredavis** [comment]
I thought I built something to help fix that in the wrapper. 

-Tre Davis




On Wed, Jul 1, 2015 at 12:10 PM -0700, "camillo777" <notifications@github.com> wrote:












Yes the Spotify Web api limit seems 50.

But it seems there is no check in your wrapper for this to throw an error. 

It would be great if your wrapper could understand that the tracks in the request are more than 50 and make multiple requests under the hood and give back the correct number of results. 

Maybe it will take more time but will save users to avoid implement their own splitting and merging  mechanism. 

Just an idea to improve it.

**Comment by thelinmichael** [comment]
You're right @tredavis, and I haven't made it to the point where I integrate your work into the wrapper. It's a good idea @camillo777, it'd make the life of the user a lot easier. I'll leave this open as an enhancement until that's done.

**Comment by camillo777** [comment]
Hi, 
as an example just to help in the mean time I have come up with this solution:
trackIds is an array of tracks IDs

```
var count = 0;
var output = [];
                      
async.whilst(
                                   function () {
//iterate over all tracks
                                            return tracksIds.length > 0;
                                   },
                                   function (callback) {
                                            var out = output;
                                            spotifyApi.getTracks(tracksIds.splice(0,50),
                                                        function(err, data) {
                                                        if (err) {
                                                                 console.error(err);
                                                        }
                                                        else {
// add returned tracks to the array "output"
                                                                 var results = data.body.tracks;
                                                                 for(var i = 0; i < results.length; i++) {
                                                                 var track = results[i];
                                                                 out.push(
                                                                    {id: track.id, name: track.name, artists: jsonpath.query(track.artists, '$..name')});
                                                                 }
                                                                 setTimeout(callback, 100);
                                                        }
                                                                 });
                                   },
                                   function (err) {
                                   if (err) {console.error(err); callback(err); }
                                   else {
// do something with the array
saveFile(outpath, output);     
callback(null);
                                   }
                                   }
                        );
```

**Comment by JMPerez** [comment]
The wrapper doesn't enforce the current limits in the API endpoints since they can vary. It doesn't provide methods for traversing a collection since this can be done in several ways and there needs to be controls in-place to prevent rate limiting. It's up to the consumer of the wrapper to handle these situations.

I'm closing this issue.
