### ISSUE TITLE
getShowEpisodes and getEpisode not working

### ISSUE THREAD

**Issue by sigesig** [thelinmichael/spotify-web-api-node#366]
Hey, am I the only one who can't get getEpisode and getShowEpisodes to work? Even when I give it the episode or show ID found in the comment of the methods. Then it just returns "non-existing id"

**Comment by MR4online** [comment]
@sigesig  You closed this. What was the problem and how did you solved it?

**Comment by shadow-light** [comment]
I got this too and needed to specify the `market` param to resolve it.
