### ISSUE TITLE
Remove track without snapshot_id

### ISSUE THREAD

**Issue by rsiegel827** [thelinmichael/spotify-web-api-node#37]
According the spotify API, snapshot_id is not mandatory. It seems to be in this interface, though. Is there a reason? If so, how do you retrieve a snapshot_id for a playlist?

**Comment by JMPerez** [comment]
@rsiegel827 The `snapshot_id` is not mandatory in that endpoint. What you can do is provide an empty object as the `options` parameter when calling `removeTracksFromPlaylist`.
