### ISSUE TITLE
SpotifyWebApi.prototype.getPlaylistTracks does not respect offset nor limit queries

### ISSUE THREAD

**Issue by BrianSantoso** [thelinmichael/spotify-web-api-node#374]
```
spotifyApi.getPlaylistTracks(playListId, {
    offset: 10, 
    limit: 5 
})
```
Although href property of the response object will apply the search queries (e.g. https://api.spotify.com/v1/playlists/{playlist_id}/tracks?offset=10&limit=5), the response will always return the first 100 tracks regardless of the values specified

**Comment by do1tsp** [comment]
Have you solved the Problem with Limit and offset?

In the flow i have seen the params don´t exist!

**Comment by 012ddd** [comment]
`getPlaylistTracks` will misbehave if used with a playlist ID that has the "?si=" parameter (now added by default when copying the URL from spotify). In that case, I think it uses the `getPlaylist` endpoint instead which ignores offset.
Could be the same issue.
