### ISSUE TITLE
Trouble with Invalid redirect URI

### ISSUE THREAD

**Issue by estock** [thelinmichael/spotify-web-api-node#39]
I'm following the code in the example and using express ... when receive the callback from spotify, I call the following function

```
app.get('/auth/spotify/callback',
  function(req, res){
    // The request will be redirected to spotify for authentication, so this
    // function will not be called.

    /* Read query parameters */
    var authorizationCode  = req.query.code; // Read the authorization code from the query parameters
    var state = req.query.state; // (Optional) Read the state from the query parameter

    console.log('authorizationCode ' + authorizationCode);
    console.log('state ' + state);

    spotifyApi.authorizationCodeGrant(authorizationCode)
      .then(function(data) {

        // Set the access token and refresh token
        console.log('The token expires in ' + data['expires_in']);
        console.log('The access token is ' + data['access_token']);
        console.log('The refresh token is ' + data['refresh_token']);

        spotifyApi.setAccessToken(data.body['access_token']);
        spotifyApi.setRefreshToken(data.body['refresh_token']);

        res.redirect('/home');

        // Save the amount of seconds until the access token expired
        tokenExpirationEpoch = (new Date().getTime() / 1000) + data.body['expires_in'];
        console.log('Retrieved token. It expires in ' + Math.floor(tokenExpirationEpoch - new Date().getTime() / 1000) + ' seconds!');
      }, function(err) {
        console.log('Something went wrong when retrieving the access token!', err.message);
        //res.redirect('/home');
        console.log('Something went wrong when retrieving the access token!', err);
      });
  });
```

I've tripple checked that the URI is actually added to the whitelist and that I am setting it when I instantiate everything 
```
var spotifyApi = new SpotifyWebApi({
  clientId : client_id,
  clientSecret : client_secret,
  redirectUri : 'http://www.example.com/callback'
});
```

I can't figure out for the life of me why it keeps throwing this error

 
```
 name: 'WebapiError',
  message: 'invalid_grant: Invalid redirect URI',
  statusCode: undefined }
```

**Comment by JMPerez** [comment]
@estock Sorry for the late reply. I'm trying to catch up with the opened issues and PRs. Did you manage to fix this issue?

**Comment by YerayRD** [comment]
Hi guys, did you manage to fix this issue? I have been stuck for a while trying to simply refresh an access token and the answer error seems similar so I guess they are related issues. 

"Something went wrong when retrieving the access token! invalid_grant: Invalid authorization code"

I have been using the authorizationCodeGrant() method, and in the analysis I have checked, it seems that the execution of the HttpManager.post call, the result is not valid or something goes wrong. Maybe this little info can give you some insights.

Looking forward for your patch or some indications
Thanks

**Comment by erratik** [comment]
I'm also having this issue :/

**Comment by jgornick** [comment]
@estock Did you add the redirect URI to your Spotify Application at https://developer.spotify.com/my-applications?

**Comment by AlexCatch** [comment]
This issue is happening to me, callback URI is in Spotify application and information is all correct.
I'll look into this issue some more.

**Comment by JMPerez** [comment]
I'm closing this issue since there is little that can be done at the wrapper level. My guess is that the problems are due to (a) not setting up correctly the application on [My Applications](https://developer.spotify.com/my-applications) or (b) some temporary issue in Spotify's Web API.
