### ISSUE TITLE
Retrieve "Recommended" songs endpoint

### ISSUE THREAD

**Issue by Muh9049** [thelinmichael/spotify-web-api-node#407]
On the Spotify app, usually in a playlist, you will see "recommended" songs. Is there any way to get an array of recommended songs with this library based on an array of songs? I can't seem to find it anywhere on the docs.

**Comment by kevinguebert** [comment]
There is the `getRecommendations` function where one can pass in `seed_artists`, `seed_tracks`, or `seed_genres`. https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/spotify-web-api.js#L738

**Comment by Muh9049** [comment]
Thanks! The feature is working great for one of my projects.
