### ISSUE TITLE
Improper encoding for getPlaylist causes the request to fail.

### ISSUE THREAD

**Issue by UnbounDev** [thelinmichael/spotify-web-api-node#41]
In this request `https://api.spotify.com/v1/users/spotify_españa/playlists/6WCc127FLZ5hztL9gpFT3j` the playlist owner `spotify_españa` has an accented character, when passed through the library this causes a `400` response due to the character encoding of that string. I'm currently mitigating this by calling`encodeURIComponent(<playlist owner>)` before calling `getPlaylist` - but really this should be handled by `spotify-web-api-node`.

**Comment by JMPerez** [comment]
@UnbounDev You are right. For some reason, the [client-side JS wrapper](https://github.com/JMPerez/spotify-web-api-js) does work (I guess the browser does the conversion automagically).
