### ISSUE TITLE
getMe function doesn't work correctly (403)

### ISSUE THREAD

**Issue by Erayyy** [thelinmichael/spotify-web-api-node#421]
Hey there!

I've been working on a project using react and came to an issue when I started using the actual methods to pull some data out of the access token.

My first attempt to actually get stuff done with the api was by using the "getMe" method. And starting by the first step of the fun-part, I already got another error looking like this:

![image](https://user-images.githubusercontent.com/26624740/136055818-bbf4c0ff-fb17-4f9c-aa9f-2a917f83aa6a.png)

The access token can't be the problem. I've compared it by looking wheter my very first generated refresh token is the same as the access token and it is so.

I've first tried using every single scope, then reduced it to the only two scopes required for the getMe method, which are "user-read-private" and "user-read-email".

Also, setting the access token to the API doesn't seem to be the problem here, the issue only appears when  I’m trying to call the method.

If there are any more informations needed to solve this problem, feel free to hit me up and I'll respond as fast as possible.

I'd be grateful about every help I can get :)

**Comment by Erayyy** [comment]
Component using getMe:

    const spotifyApi = new SpotifyWebApi();
    const accessToken = useAuth(code);
    console.log(accessToken);

    if (accessToken === undefined) { return null }
    else {

    spotifyApi.setAccessToken(accessToken);

        spotifyApi.getMe()
    .then(function(data) {
        console.log('Some information about the authenticated user', data.body);
    }, function(err) {
        console.log('Something went wrong!', err);
    });

    return(
        <div>
            { code }
        </div>
    )

  useAuth hook:
  
      import { useState, useEffect } from 'react';
      import axios from 'axios';
      
      export default function useAuth( code ) {
          const [accessToken, setAccessToken] = useState()
          const [refreshToken, setRefreshToken] = useState()
          const [expiresIn, setExpiresIn] = useState()


    useEffect(() => {
        axios.post('http://localhost:3001/login', { 
                code,
            })
            .then(res => {
                setAccessToken(res.data.accessToken)
                setRefreshToken(res.data.refreshToken)
                setExpiresIn(res.data.expiresIn)
                window.history.pushState({}, null, "/")
            })
            .catch(() => {
                window.location = "/"
        })
    }, [code])

    useEffect(() => {
        if(!refreshToken || !expiresIn) return
        const interval = setInterval(() => {
        axios.post('http://localhost:3001/refresh', { 
                refreshToken,
            })
            .then(res => {
                setAccessToken(res.data.accessToken)
                setExpiresIn(res.data.expiresIn)
            })
            .catch(() => {
                window.location = "/"
            })
        }, (expiresIn - 60) * 1000)

        return() => clearInterval(interval)
    }, [refreshToken, expiresIn])

    return accessToken


server:

    app.post('/login', (req, res) => {
        const code = req.body.code
        const spotifyApi = new SpotifyWebApi({
            clientId: '------------------------------------------',
            clientSecret: '--------------------------------------',
            redirectUri: 'http://localhost:3000'
        })
  
      spotifyApi
      .authorizationCodeGrant(code)
      .then(data => { console.log(data);
          res.json({
              accessToken: data.body.access_token,
              refreshToken: data.body.refresh_token,
              expiresIn: data.body.expires_in
          })
      })
      .catch(() => {
          res.sendStatus(400)
      })
    })
  
    app.post('/refresh', (req, res) =>{
        const refreshToken = req.body.refreshToken
        const spotifyApi = new SpotifyWebApi({
            clientId: '----------------------------------------------',
            clientSecret: '------------------------------------------',
            redirectUri: 'http://localhost:3000',
            refreshToken,
        })
    
        spotifyApi
            .refreshAccessToken()
            .then(data => {
                res.json({
                    accessToken: data.body.accessToken,
                    expiresIn: data.body.expiresIn,
                })
            })
            .catch(() => {
                res.sendStatus(400)
            })
        })
    app.listen(3001)

**Comment by makhshari** [comment]
Same issue here! It seems that getMe only works for the user who owns the authorized app. I assume the authorized app should work with different users as well.
