### ISSUE TITLE
get the date a song was saved

### ISSUE THREAD

**Issue by ayush-shrivastava003** [thelinmichael/spotify-web-api-node#429]
I'm trying to make an app that visualizes data from your liked songs. One of the things I wanted to chart was the data songs were saved but I can't find anything on the Spotify docs about this. Does anyone know if this is possible?

**Comment by andyruwruw** [comment]
I don't think this is appropriate to label as an issue for `spotify-web-api-node`.  This is more a question about on Spotify's API. You should delete this issue.

That being said the endpoint to [get your saved tracks](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-saved-tracks) returns the date each song was added. I think you meant to say "date songs were saved"? You can try the [endpoint here](https://developer.spotify.com/console/get-current-user-saved-tracks)!
