### ISSUE TITLE
Invalid Limit

### ISSUE THREAD

**Issue by rodrigoricky** [thelinmichael/spotify-web-api-node#431]
Currently, I am trying to pick a random song from a playlist, and that playlist has like 10,000 songs in it. When I set the limit above 100, it gave me an `invalid limit` error.

Code:
 ```js
spotifyApi.getPlaylistTracks('6yPiKpy7evrwvZodByKvM9', { offset: 1, limit: 100, fields: 'items' })
  	.then(
        function(data) {
       		let randomnumber = Math.floor((Math.random() * 99) + 1);
		let testing = data.body.items[randomnumber].track.id
     		 //console.log('The playlist contains these tracks', testing);
        message.reply(`Here's a random Spotify Song! https://open.spotify.com/track/${testing}`)
   			
		       },
      function(err) {
      console.log('Something went wrong!', err);
    });
```
Console Error: 
![image](https://user-images.githubusercontent.com/89636767/146678588-ef1862d7-8733-4c85-9b4c-8343bd28e5b8.png)

**Comment by rodrigoricky** [comment]
If this is necessary info, this is the playlist link: https://open.spotify.com/playlist/6yPiKpy7evrwvZodByKvM9?si=6aa16b0d11bc4a15

**Comment by eliob83** [comment]
According to [Spotify API documentation](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-playlists-tracks), one can limit by a maximum of 50 tracks at once. Therefore you should use the _offset_ parameter to browse your playlist step by step.

**Comment by rodrigoricky** [comment]
Hey there,

Thanks so much for reaching out! This auto-reply is just to let you know…

I received your email and will get back to you with a response as soon as possible. That's usually within a couple of hours. Evenings and weekends may take me a little bit longer.

If this is an urgent matter, you can message me on Facebook or please feel free to email me on my other account

I am looking forward to chatting with you!

Cheers,
Ricky
