### ISSUE TITLE
Pagination issue for getUserPlaylists()

### ISSUE THREAD

**Issue by Cal-culator** [thelinmichael/spotify-web-api-node#439]
Spotify, by default, limits the length of the playlist array to 20. Using getUserPlaylists() function only returns 20 playlists.

**Comment by simondebbarma** [comment]
Kinda funny we both have the same query. I tried using `{ limit : 50, offset : 50 }` as recommended in the docs but I'm getting the following error.

```
Unhandled Runtime Error

WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: No token provided.
```

I would like to know how to get ALL user playlists.

**Comment by simondebbarma** [comment]
Welp, figured it out 5 minutes after typing the above.

Do something like this.
```
spotifyApi.getUserPlaylists({ limit: 50, offset: 0 })
```
Then you can write logic to increase the offset by 50 everytime until you reach the end of the playlists. The limit max is 50 tho.

**Comment by Cal-culator** [comment]
Ah ok. This is really helpful! Thanks a lot!

**Comment by lucasrmagalhaes** [comment]
@simondebbarma thanks!
