### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by twilly86** [thelinmichael/spotify-web-api-node#46]
Hey,

I'm having issues using the refresh token to get a new access token.  Is there anythign I need to do besides using the setRefreshToken method?

Thanks,

Tom

**Comment by JMPerez** [comment]
@twilly86 Not really, apart from calling the `refreshAccessToken()` function. Are you sure you are setting a valid refresh token?

**Comment by twilly86** [comment]
i found the refresh token logic in your example scripts.  I'm good to go now, thanks!

**Comment by JMPerez** [comment]
@twilly86 great! Thanks for letting us know!
