### ISSUE TITLE
How can i play a track

### ISSUE THREAD

**Issue by ngoc2003** [thelinmichael/spotify-web-api-node#494]
hi, after log in successfully, i call .play() to play a track with    ` context_uri: "spotify:album:0sNOF9WDwhWunNAHPD3Baj"`,
but i got 403 issue and it required a premium account. Is this method only work with premium spotify account?

**Comment by yangcui23** [comment]
it do seems like the only way , I had to purchase the premium in order to use the Spotify Web Player
