### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by fmorett** [thelinmichael/spotify-web-api-node#498]
I'm getting the following error when loading the tracks of a specific playlist.

An error occurred while communicating with Spotify's Web API.
Details: Server error...

Important: this error occurs only with this concrete show.

Steps to reproduce:
```typescript
import SpotifyWebApi from "spotify-web-api-node";

async function main() {
  const client_id = ""; // add client id
  const client_secret = ""; // add client secret

  const api = new SpotifyWebApi({
    clientId: client_id,
    clientSecret: client_secret
  });
  const data = await api.clientCredentialsGrant();
  api.setAccessToken(data.body["access_token"]);

  // this line throws an error
  const result = await api.getShowEpisodes("03dvsetYGw4IKbrtRhWPcQ");
}

main().catch(console.error)
```

**Comment by hjdeheer** [comment]
Also getting a WebApi error, since today, when communicating with the Spotify Web API. What is going on? 

![image](https://github.com/thelinmichael/spotify-web-api-node/assets/44620257/7001aeab-da22-4d69-a5af-9e48296e8e6a)


Update: Seems to be fixed now. Probably a server-side error at Spotify,  still I would like a better error message that shows the cause of the error.

**Comment by Moethantko** [comment]
Hey. Do you guys have issues with AuthorizationCodeGrant? When I login with my other Spotify accounts, I'm not getting the access token when I call the method _spotifyApi.authorizationCodeGrant(code)_. The weird thing is that it used to be work a few months ago. It just starting causing issues recently. Please let me know if you have any suggestions!

**Comment by fmorett** [comment]
Yes works again for me. Error Message is super weird though.

**Comment by fmorett** [comment]
Can be closed since this is a spotify issue IMO and not a library issue
