### ISSUE TITLE
search() method doesn't work properly

### ISSUE THREAD

**Issue by AlcuZan** [thelinmichael/spotify-web-api-node#61]
Hi,

I'm trying to use the search() method and it basically gives me a mostly empty object.
This is what I get:

```
{ tracks:
   { href: 'https://api.spotify.com/v1/search?query=Du+bist+sch%C3%B6n&offset=1&limit=1&type=track',
     items: [ [Object] ],
     limit: 1,
     next: 'https://api.spotify.com/v1/search?query=Du+bist+sch%C3%B6n&offset=2&limit=1&type=track',
     offset: 1,
     previous: 'https://api.spotify.com/v1/search?query=Du+bist+sch%C3%B6n&offset=0&limit=1&type=track',
     total: 2041 } }
```

Here's the code I'm executing with Git Bash (not gonna share my clientId and clientSecret of course, but they are there and correct): 

```
var SpotifyWebApi = require('spotify-web-api-node');
var spotifyApi = new SpotifyWebApi({
	clientId: <clientID>,
	clientSecret: <clientSecret>,	
        redirectUri: 'http://localhost:8888/callback',
});
spotifyApi.search('Du bist schön', ['track'], { limit : 1, offset: 1}, function(err, data) {
	if (err) {
		console.error(err);
	} else {
	console.log(data.body)
	}
});
```
If I try this `data.body["tracks"]` it gives me more information:

```
{ href: 'https://api.spotify.com/v1/search?query=Du+bist+sch%C3%B6n&offset=0&limit=1&type=track',
  items:
   [ { album: [Object],
       artists: [Object],
       available_markets: [Object],
       disc_number: 1,
       duration_ms: 228213,
       explicit: false,
       external_ids: [Object],
       external_urls: [Object],
       href: 'https://api.spotify.com/v1/tracks/5PJeAJAw8YFUesmwARqn9Y',
       id: '5PJeAJAw8YFUesmwARqn9Y',
       name: 'Du bist schön',
       popularity: 68,
       preview_url: 'https://p.scdn.co/mp3-preview/04b971fb3e032f162d0096e442073a25c085cfb6',
       track_number: 11,
       type: 'track',
       uri: 'spotify:track:5PJeAJAw8YFUesmwARqn9Y' } ],
  limit: 1,
  next: 'https://api.spotify.com/v1/search?query=Du+bist+sch%C3%B6n&offset=1&limit=1&type=track',
  offset: 0,
  previous: null,
  total: 2041 }


```
but that's still not everything, as you can see. I tried using an access token (I have another function that gives me the audio features of a song) but I get the same result. I also tried using promises but still the same.
What am I doing wrong here? Please keep in mind that I'm fairly new to JavaScript and Node.
Also I do not really need everything, mostly I'd like to get the artist, name of the track and the id. How do I get only these things?

**Comment by JMPerez** [comment]
Hi @AlcuZan!

I see that you are pasting both the code to get the first one (limit=1, offset=0) and also the second one (limit=1, offset=1). It is a minor issue but makes it more difficult to find out exactly what problem you are having.

By the looks of it the API is working perfectly. You are getting track objects when searching tracks.

If you want to get the artist, name of the track and id, you can do:

```js
var track = data.body.tracks.items[0]; // beware items can be empty and you would need to check for this case
var artistName = track.artists[0].name; // a track always has a list of artist objects with at least one of them
var trackName = track.name;
var trackId = track.id;
```

I'm going to close this ticket since I can't see any problem in the behaviour of the wrapper. Feel free to reopen it if you find any issue.
