### ISSUE TITLE
Getting 404 errors when attempting to access a user's playlists

### ISSUE THREAD

**Issue by jswny** [thelinmichael/spotify-web-api-node#62]
I'm using Node version 5.5.0, and `spotify-web-api-node` version 2.3.0. I'm using the following function to get the playlists from my own Spotify account.

```javascript
var SpotifyWebApi = require('spotify-web-api-node');
var clientId = '<client id>';
var clientSecret = '<client secret>';

var spotifyApi = new SpotifyWebApi({
	clientId: clientId,
	clientSecret: clientSecret
});

function getUserPlaylists(userId) {
	spotifyApi.clientCredentialsGrant()
		.then(function(data) {
			spotifyApi.setAccessToken(data.body['access_token']);
			spotifyApi.getUserPlaylists(userId)
				.then(function(data) {
					console.log(data);
				}, function(err) {
					console.log('Something went wrong!', err);
				});
		}, function(err) {
			console.log('Something went wrong when retrieving an access token', err);
		});
}
```

However, whenever I call this function with my own Spotify user ID (I signed up with Facebook), I get the following error: `Something went wrong! { [WebapiError: Not found.] name: 'WebapiError', message: 'Not found.', statusCode: 404 }`. Other API functions work still, but all of a sudden this one ceased to work even though I haven't touched my server or the code for my server since it was working well. I checked the endpoints in the `spotify-web-api-node` source code and they seem to still be correct for `getUserPlaylists`.

**Comment by JMPerez** [comment]
@jswny What is the `user_id` you are trying? I'm checking the source code and the endpoint looks correct. I'm wondering if some character in the user_id is breaking the url requested.

**Comment by jswny** [comment]
@JMPerez I thought about that too. However, I didn't actually try encoding the user ID though because it's just numbers (because I'm signed in with Facebook). I'm using my user like so: `getUserPlaylists('12186155030')`.

**Comment by JMPerez** [comment]
@jswny This should work without any problems. I just checked using [the web api console](https://developer.spotify.com/web-api/console/get-playlists/?user_id=12186155030) and the Web API returns playlists data for that user, as expected.

I also tried it using the wrapper, with positive results:

```js
var spotifyApi = new SpotifyWebApi();
spotifyApi.setAccessToken('BQAQngO....jYv4g');
spotifyApi.getUserPlaylists('12186155030').then(function(data) {
  console.log(data.body);
});
```

which outputs:

```
{ href: 'https://api.spotify.com/v1/users/12186155030/playlists?offset=0&limit=20',
  items:
   [ { collaborative: false,
       external_urls: [Object],
       href: 'https://api.spotify.com/v1/users/12186155030/playlists/7Mwujrto3KiamiiBwbUhT8',
       id: '7Mwujrto3KiamiiBwbUhT8',
       images: [Object],
       name: 'Peep Game',
       owner: [Object],
       public: true,
       snapshot_id: 'ENqNKgOb1d0CIvPJjb7SE7Le2ApBz6r/eGU11/E41fGyOVNwzQu2SsN7SUKM9Vef',
       tracks: [Object],
       type: 'playlist',
       uri: 'spotify:user:12186155030:playlist:7Mwujrto3KiamiiBwbUhT8' },
     { collaborative: false,
     ...
```

Just to double check, it might be useful to print out the actual URL that is being requested, eg printing the value of `uri` in `HttpManager._makeRequest()`.

**Comment by jswny** [comment]
Well, I have no idea what happened. I was debugging around with the code on my local machine and suddenly it started working. I narrowed the problem down to getting the playlist data for each playlist returned by `spotifyApi.getUserPlaylists()` using `spotifyApi.getPlaylist()` because I was getting an error there. Then all of a sudden, I reset the process on my local machine after making some changes and it just worked. I have no idea why. I went onto my website (which is on a completely different production server which I have not touched, not even using SSH, throughout this whole process), and magically, it works. I'm baffled. The only thing I could possibly think of is that while I was clicking around in the Spotify app I made some playlist public which wasn't before and that made it so my code could loop through getting the playlist data of each playlist?

**Comment by jswny** [comment]
Once again, after having changed absolutely nothing on my production server, I'm getting the same error again. Testing my site on my local machine yields the same results. Upon further investigation, I've found the problem. After I grab the user's playlists, I'm iterating over them like this: 

```
spotifyApi.getUserPlaylists(userId)
	.then(function(data) {
		var playlists = data.body.items
		var playlistsArr = new Array()
		var count = 0
		playlists.forEach(function(playlist) {
			spotifyApi.getPlaylist(userId, playlist.id)
				.then(function(data) {
					playlistsArr.push({
						name: playlist.name,
						id: playlist.id,
						img: playlist.images[2].url,
						followers: data.body.followers.total,
						total_tracks: playlist.tracks.total
					})
					if (count == playlists.length - 1) {
						callback(playlistsArr)
					}
					count++
				}, function(err) {
					console.log('Something went wrong retrieving an individual playlist!', err)
				})
		})
	}, function(err) {
		console.log("Something went wrong retrieving the user's playlists!", err)
	})
```

However, the page would hang and never load, which was the reason I started noticing this problem. Turns out, some of the Spotify playlists that I followed were made public on my profile, thus they were pulled into what my code thought was an array of _my_ playlists. Then, when I tried to use `getPlaylist(userId, playlist.id)` it would hang. That's because those other playlists that I had followed were not mine, so when I looped through one of those, the whole script would hang. To fix this, I've made all of those secret but you could just as easily check each playlist for the property `collaborative` or something similar before looping through each one. That would explain the 404 errors as well because the API was trying to access a playlist that didn't exist from my user ID. This turned out to be my incompetence, nothing wrong with any of the tools I was using. Hopefully this helps others to fix this mistake more easily. Thank you @JMPerez for the help.

**Comment by stfnlzvn** [comment]
Ran into the same problem when using getPlaylistTracks(). Fixed it by passing playlist.owner.id rather than user.id
