### ISSUE TITLE
replaceTracksInPlaylist is missing a range_start parameter 

### ISSUE THREAD

**Issue by amarcher** [thelinmichael/spotify-web-api-node#64]
When the `replaceTracksInPlaylist` method is invoked, Spotify returns an error that the request is missing a `range_start` parameter. Looking at the Spotify API documentation on [replace a playlist's tracks](https://developer.spotify.com/web-api/replace-playlists-tracks/), it would not appear that this field is required, except that it's actually using the same endpoint (https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks) as [reorder tracks](https://developer.spotify.com/web-api/reorder-playlists-tracks/), for which range_start is a required param.

The fix would likely be to add a range_start parameter (hard-coded to 0?) to the body of the post.

spotifyApi.replaceTracksInPlaylist(userId, playlistId, trackIds)

{ [WebapiError: Missing range_start parameter]
  name: 'WebapiError',
  message: 'Missing range_start parameter',
  statusCode: 400 }

**Comment by amarcher** [comment]
#65

**Comment by JMPerez** [comment]
@amarcher The endpoint for replacing all tracks in a playlist doesn't require `range_start`. It seems to work for me:

```js
var spotifyApi = new SpotifyWebApi();
spotifyApi.setAccessToken('my_access_token');
spotifyApi.replaceTracksInPlaylist('jmperezperez', '01kNoYcRkCcEKaqEW7hXCR', [
  'spotify:track:4kJP8Z888wREJ8bRMWNMuk',
  'spotify:track:16taQAqrrfqCwbkbKFr2OH'
]).then(function(data) {
    console.log(data);
  }, function(err) {
    console.log(err);
  });
```

outputs

```js
{ body: '',
  headers:
   { server: 'nginx',
     date: 'Mon, 27 Jun 2016 17:24:08 GMT',
     'content-length': '0',
     connection: 'close',
     'cache-control': 'private, max-age=0',
     'access-control-allow-origin': '*',
     'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE',
     'access-control-allow-credentials': 'true',
     'access-control-max-age': '604800',
     'access-control-allow-headers': 'Accept, Authorization, Origin, Content-Type',
     'x-content-type-options': 'nosniff',
     'strict-transport-security': 'max-age=31536000;' },
  statusCode: 201 }
```

What is the value of your `trackIds` variable?

Since there doesn't seem to be an issue with this function, I will close the issue for now. But feel free to reopen it if you want to add any extra information.
