### ISSUE TITLE
invalid request for getRecomendations

### ISSUE THREAD

**Issue by kyv** [thelinmichael/spotify-web-api-node#66]
Calling `getRecomendations` from the example in source code throws an error. In the example below, `getAudioFeaturesForTracks` will return a valid response while `getRecommendations` will return the following err:

```js
{ [WebapiError: invalid request]
  name: 'WebapiError',
  message: 'invalid request',
  statusCode: 400 }
```

```js
spotifyApi.clientCredentialsGrant()
  .then(function(data) {
    console.log('The access token expires in ' + data.body['expires_in']);
    console.log('The access token is ' + data.body['access_token']);

    // Save the access token so that it's used in future calls
    spotifyApi.setAccessToken(data.body['access_token']);
  }, function(err) {
        console.log('Something went wrong when retrieving an access token', err);
  })
  .then(function(){
    spotifyApi.getAudioFeaturesForTracks(['38P3Q4QcdjQALGF2Z92BmR', '2HO2bnoMrpnZUbUqiilLHi']).then(function(data){
      console.log(data.body.audio_features)
    }, function(err){
      console.log(err)
    })
    spotifyApi.getRecommendations({ min_energy: 0.4, seed_artists: ['6mfK6Q2tzLMEchAr0e9Uzu', '4DYFVNKZ1uixa6SQTvzQwJ'], min_popularity: 50 })
      .then(function(data) {
        console.log(data);
      }, function(err) {
        console.log(err);
      });
  });
```

**Comment by JMPerez** [comment]
Thanks for the report @kyv.

The issue seems to be in the library we use to make the request, which doesn't serialize the array of `seed_artists` like the browser does. As a workaround, pass a string `seed_artists: '6mfK6Q2tzLMEchAr0e9Uzu,4DYFVNKZ1uixa6SQTvzQwJ'` while we add a `join()`in the `getRecommendations()` function.

**Comment by kyv** [comment]
Thanks for the quick response. Passing a string as you say works for me. But just a note, a space between the two seeds will break it. Thanks again.

**Comment by JMPerez** [comment]
@kyv yes, that will break since that format is not supported.

There is an open PR to get this fixed. I will update this issue when it is merged and the patches version published.
