### ISSUE TITLE
2.3.2 broke authorizationCodeGrant

### ISSUE THREAD

**Issue by erezny** [thelinmichael/spotify-web-api-node#72]
with 2.3.2 I would receive a blank error message when calling authorizationCodeGrant as a promise. 2.3.1 works fine.

**Comment by thelinmichael** [comment]
I'll look into it, thanks for raising it @erezny!

**Comment by JMPerez** [comment]
There is a missing `options.data` in [http-manager](https://github.com/thelinmichael/spotify-web-api-node/blob/22119bc98b9f1505110a9f9ac191123d3434bd99/src/http-manager.js#L68) and we don't seem to pass the form data as `x-www-form-urlencoded` through superagent.

I'm trying to find out how to pass it properly.

**Comment by JMPerez** [comment]
@erezny This should be now fixed. Thanks for reporting it!
