### ISSUE TITLE
no serverMethods

### ISSUE THREAD

**Issue by gilbarbara** [thelinmichael/spotify-web-api-node#79]
Hello,
I'm trying to authenticate an user but the resulting instance doesn't have any of the server methods.

```javascript
import SpotifyWebApi from 'spotify-web-api-node';

const credentials = {
  clientId: `clientId`,
  clientSecret: `clientSecret,`
  redirectUri: 'http://localhost:3000/callback'
};

const SpotifyApi = new SpotifyWebApi(credentials);
...

SpotifyApi.authorizationCodeGrant(...code);
undefined

```

**Comment by JMPerez** [comment]
@gilbarbara Are you bundling the code to be run in the browser, or in the server?

**Comment by gilbarbara** [comment]
hey @JMPerez 
browser with webpack.

**Comment by JMPerez** [comment]
The reasoning behind this is that the functions that expose the client secret shouldn't be run client-side. The secret key shouldn't be shared and remain secret. You should use it server-side to the exchange of the code into an access token.

When we made this library _browserifiable_ we tried to make sure that we didn't support these bad practices.

**Comment by gilbarbara** [comment]
You should put that disclaimer in the readme.
Anyway, I was just testing it locally and would not expose my secret..

**Comment by JMPerez** [comment]
Sure, I will include it in the readme to clarify it better.

Happy hacking!

**Comment by JMPerez** [comment]
And now it is explained in the README.
