### ISSUE TITLE
authorizationCodeGrant seems timing out?

### ISSUE THREAD

**Issue by rn2dy** [thelinmichael/spotify-web-api-node#80]
We have a auth flow where our android app send the auth code to the server, and server makes a authorizationCodeGrant api call to get the accessToken and refreshToken, currently the call is timing out. Is this a correct flow and is it suppose to work, note that the redirect URI on android is not a http url but a custom scheme.

**Comment by JMPerez** [comment]
Hi @rn2dy! Did you manage to get it fixed? What was the problem?

**Comment by rn2dy** [comment]
@JMPerez it works, there is an unhandled exception and thats all. But thanks for the follow up 👍

**Comment by JMPerez** [comment]
@rn2dy If you think that is something the wrapper should be handling, let me know.
