### ISSUE TITLE
this.getRecommendations returns an "invalid request" error

### ISSUE THREAD

**Issue by alexwohlbruck** [thelinmichael/spotify-web-api-node#83]
When running the getRecommendations function using the wrapper, an error is returned saying it is an invalid request. Turns out, it's because the seed_artists, seed_genres, and seed_tracks are being sent as arrays in the query string rather than comma separated strings. This is simply solved by adding `.join(',')` on the end of the arrays that are sent, but this isn't specified in the docs. Please either update the dogs or have the arrays turned into strings automatically. That would have saved me a lot of headache.

**Comment by JMPerez** [comment]
@alexwohlbruck this seems to be a duplicate of https://github.com/thelinmichael/spotify-web-api-node/issues/66, which was fixed and released in version 2.3.1.

Could you verify you are using the latest version of the package?

**Comment by alexwohlbruck** [comment]
@Yep, that's it. I'm running 2.3.0.
