### ISSUE TITLE
A way to access older snapshot_ids in retrospect?

### ISSUE THREAD

**Issue by modkaffes** [thelinmichael/spotify-web-api-node#92]
I was wondering if the ability to access older states of a playlist (eg. Discover Weekly) is implemented. 

I'm aware of this [IFTTT applet](https://ifttt.com/applets/313481p-save-your-discover-weekly-tracks-to-a-playlist), but if I understand this correctly, it works from the point you enable it forward.

So, can I access older snapshot_ids?

**Comment by JMPerez** [comment]
@modkaffes I'm very sorry for the late reply. This is not something provided by this wrapper since it's not exposed by the Spotify's Web API. You might want to file a feature request on https://github.com/spotify/web-api

**Comment by modkaffes** [comment]
@JMPerez Thanks for the clarification!
