### ISSUE TITLE
Receiving 403 error when running create playlist method. 

### ISSUE THREAD

**Issue by abelmark** [thelinmichael/spotify-web-api-node#98]

**Comment by mdoxey06** [comment]
I'm also receiving this error, how did you end up resolving this?

**Comment by sdzharkov** [comment]
Same Question - what's the fix?

**Comment by RHeijnen** [comment]
There is a special place in hell for people who close tickets without sharing the solution.

**Comment by DiegOrtega** [comment]
wtf m8, I have the same problem, please help!
